### ISSUE TITLE
las 1.2 vs 1.4

### ISSUE THREAD

**Issue by opetrik71** [laspy/laspy#100]
Hi,
I am using 1.5.1 version and there is a difference if I read las_1.2 or las_1.4 files:
the **infile.blue** and **infile.green** colour values are reversed. 
If I create v1.2 from v1.4 (with las2las) the colour values will be the correct place.
Have anybody ever experienced this?

**Comment by grantbrown** [comment]
Please post a reproducible example - I can't reproduce this.
