### ISSUE TITLE
Cant import pycrown - spyder

### ISSUE THREAD

**Issue by DavidEic** [laspy/laspy#107]
Hi!

So I installed pycrown and all requirements. The test runs fine and returns no errors. 
Unfortunately when I try to "from pycrown import PyCrown" in spyder I get :
cannot import name 'PyCrown' from 'pycrown' (unknown location)

How to fix this?

I am new to the coding world so please excuse me if its a stupid questions.

Thanks in advance!
David

**Comment by kbevers** [comment]
Not a stupid question, just not the right place to ask it. This page concerns the Laspy project - you need to find the the support forum for pycrown.

Closing this as not relevant to laspy.
