### ISSUE TITLE
How to save out scaled points?

### ISSUE THREAD

**Issue by CUBICinfinity** [laspy/laspy#108]
I can write something like `las_file.X = las_file.x` or `output_file.X = scaled_X`, but as is mentioned in the documentation, that results in rounding errors. How can I save a new las file with correctly scaled floating value points?

**Comment by zwnk** [comment]
can you give an example for the rounding error?

**Comment by CUBICinfinity** [comment]
> room4F.X[0]
285471

> room4F.x[0]
28.5471

> room4F.X[0] = room4F.x[0]

> room4F.X[0]
28

**Comment by CUBICinfinity** [comment]
I think maybe I have to change the type in the header. Not sure how to do that yet.

**Comment by grantbrown** [comment]
Strictly speaking, it's not possible to store the data in a pre-scaled double precision format in the X, Y, and Z dimensions defined by the LAS format specification. They're defined to be integers, so the "LAS" way to store the data is integers + scaling factors. 

What you're seeing in the example you posted isn't a "rounding error", it's data being truncated when converted from double precision floating point to integer format. You can work with the lower case dimensions, in which case laspy will apply the scaling factors (file_object.header.scale) to store the appropriate integer format:

    >>> new_dim = outFile.x
    >>> new_dim[1] = 2.123123
    >>> outFile.x = new_dim
    >>> outFile.x[1]
    2.123123


This is not exact, as it will depend on the precision of your scaling factors. If you have a need to exactly store double precision point data, I'd recommend using a different format. Alternatively, you can define additional double precision dimensions, but it will inflate your file size by a lot:

    import laspy
    # Open file (version 1.4)
    inFile = laspy.file.File("./simple1_4.las", mode = "r")
    # Create an output file
    outFile = laspy.file.File("./output.las", header = 
            inFile.header, mode = "w")
    # Define a double precision dimension for your new scaled data
    outFile.define_new_dimension(name="scaled_x", data_type = 10,
            description = "Scaled X")

    # Copy any dimensions you want to keep as-is
    outFile.X = inFile.X
    outFile.Y = inFile.Y
    outFile.Z = inFile.Z
    # Set the value of the double precision dimension
    outFile.scaled_x = inFile.x
    # Close the files
    outFile.close()
    inFile.close()

**Comment by CUBICinfinity** [comment]
Thanks!
