### ISSUE TITLE
Unhelpful error message: "Laszip was not found on the system"

### ISSUE THREAD

**Issue by kannes** [laspy/laspy#109]
If "laszip is not installed" and the user tries to read a laz file, laspy will throw the following exception message in their face:

`LaspyException: Error mapping file: Laszip was not found on the system`

Now what *is* Laszip? I thought it was the `LASzip[64].dll` but adding that to the path did not solve anything.

What the error message actually seems to imply is that `laszip[64].exe` (or on Linux `laszip-cli`?) is missing from the PATH. At least the error vanished once I added that.

https://github.com/laspy/laspy/pull/77/commits/b29c60b728bea9babb06a6364300b178cd8f99fa looks like that.

Please update the message to something mentioning the name of the executable that laspy failed to find.

You can see a recent example of a user being confused at https://github.com/laspy/laspy/issues/73#issuecomment-522879188

**Comment by kbevers** [comment]
> Please update the message to something mentioning the name of the executable that laspy failed to find.

Please provide a pull request with a better error message.

**Comment by kannes** [comment]
I am tentative when it comes to making PRs to projects I am not already involved or familiar with. But I guess your comment implies agreement? PR incoming.
