### ISSUE TITLE
No PyPI package for 1.6.0?

### ISSUE THREAD

**Issue by plimkilde** [laspy/laspy#113]
The changelog in this repo's README has listed a 1.6.0 release for almost a year now, but the [laspy PyPI page](https://pypi.org/project/laspy/) does not show any versions more recent than 1.5.1.

Is 1.6.0 in fact supposed to have been released? If so, it would be nice to have it uploaded to PyPI so that we can also update the [laspy conda feedstock](https://github.com/conda-forge/laspy-feedstock) which draws upon PyPI's version :-)

**Comment by kbevers** [comment]
Here you go: https://pypi.org/project/laspy/

**Comment by plimkilde** [comment]
Cool, thanks!
