### ISSUE TITLE
Unable to asign data to new dimension

### ISSUE THREAD

**Issue by schmohlo** [laspy/laspy#114]
Hello

When I'm defining a new dimension, I can see it as attribute in my file object. However I can't assign any data to it. 
```
outHeader = laspy.header.Header(file_version=1.4, point_format=8)
outFile = laspy.file.File("./test.las", mode='w', header=outHeader)
outFile.define_new_dimension("MyDim", data_type=10, description="a new dim")  

outFile.X = np.ones(3)
outFile.Y = np.ones(3)
outFile.Z = np.ones(3)
outFile.MyDim = np.ones(3)

outFile.close()
```
This results in the following error:

>   in to_las
    outFile.MyDim = np.ones(3)
  File "/home/stefan/anaconda3/envs/DL4/lib/python3.7/site-packages/laspy/file.py", line 174, in fset
    self._reader.set_dimension(name, value)
  File "/home/stefan/anaconda3/envs/DL4/lib/python3.7/site-packages/laspy/base.py", line 1225, in set_dimension
    "not found.")
laspy.util.LaspyException: Dimension: MyDimnot found.

**Comment by grantbrown** [comment]
Extra dimensions are currently coerced to lower case - fixed in [this](https://github.com/grantbrown/laspy/commit/c97ffa521f158db73a2fe1651648a7488912ffdc) commit. 

Once it passes the checks I'll issue a pull request.
