### ISSUE TITLE
Make FakeMmap a bytes-like object

### ISSUE THREAD

**Issue by kbevers** [laspy/laspy#123]
In #122 a short-term solution to #112 is provided. A long-term fix would be to make FakeMmap a bytes-like object instead of using __buffer__ attribute.

**Comment by Ring-r** [comment]
Does anybody know or remember why FakeMap is used there?

Could we use an anonymous [mmap](https://docs.python.org/3/library/mmap.html) instead of FakeMap?
```
self._mmap = mmap.mmap(-1, len(data))
self._mmap[0:len(data)] = data
```

Was there any problem with previous python or numpy packages?
