### ISSUE TITLE
Guidance to add SRS to file

### ISSUE THREAD

**Issue by glostis** [laspy/laspy#125]
Hi,

I need to create a `.las` file from programmatically generated data.

I would like to assign a SRS to my file, but it seems that all SRS-related features of `laspy` are [not implemented](https://github.com/laspy/laspy/search?q=srs&type=Code).

I should be able to do it myself by adding the VLRs by hand, as I have seen in `PDAL`'s code [which VLRs are created](https://github.com/PDAL/PDAL/blob/master/io/LasWriter.cpp#L476-L501) but I have no idea of how to generate the required GeoTIFF tags corresponding to my SRS in Python.

My use case should be quite simple as my SRS can only be a UTM zone (EPSG 326xx or 327xx).

Would anyone have any guidance on how to do this simply in Python? Or is this too complex, and I should just use `PDAL` to generate my LAS?

**Comment by hobu** [comment]
I would use PDAL. I'm obviously biased 😄 

Conda is the best way to get going with pdal. https://pypi.org/project/PDAL/ has good examples of how to drive it with Python.

```
conda install -c conda-forge python-pdal pdal
```

Advantages of PDAL
* Works for all LAS versions
* Does GeoTIFF stuff
* You can insert WKT from [pyproj](http://pyproj4.github.io/pyproj/stable/) via pipelines with full control
* Support other formats

Disadvantages of PDAL
* Not pure-Python

**Comment by glostis** [comment]
@hobu thanks for your answer!

I will follow your advice and go ahead with `pdal`, which is indeed much more powerful, but a bit trickier to install when `conda` is not an option.
