### ISSUE TITLE
How can create laspy point from numpy array?

### ISSUE THREAD

**Issue by ibrahimLearning** [laspy/laspy#127]
@kbevers 
I have a laz file, it has xyzrgb
I read it and extract:

xi=lazF.X
yi=lazF.Y
zi=lazF.Z

Now added something with xi,
xi=xi+500
Now I want to write new laz file with xi, yi, zi.
Is there any help?

**Comment by zwnk** [comment]
something like this

```
in_file = laspy.file.File(input_file, mode="r")

allPoints = in_file.points.copy()
lasScaleX = in_file.header.scale[0]
lasOffsetX = in_file.header.offset[0]
lasScaleY = in_file.header.scale[1]
lasOffsetY = in_file.header.offset[1]

for idx, record in enumerate(allPoints):
    (allPoints[idx]['point']['X'] * lasScaleX) + lasOffsetX - 500
    (allPoints[idx]['point']['Y'] * lasScaleY) + lasOffsetY - 500

out_file = laspy.file.File(output_file, mode="w", header=in_file.header)
out_file.points = allPoints
out_file.close()
```

**Comment by ibrahimLearning** [comment]
> something like this
> 
> ```
> in_file = laspy.file.File(input_file, mode="r")
> 
> allPoints = in_file.points.copy()
> lasScaleX = in_file.header.scale[0]
> lasOffsetX = in_file.header.offset[0]
> lasScaleY = in_file.header.scale[1]
> lasOffsetY = in_file.header.offset[1]
> 
> for idx, record in enumerate(allPoints):
>     (allPoints[idx]['point']['X'] * lasScaleX) + lasOffsetX - 500
>     (allPoints[idx]['point']['Y'] * lasScaleY) + lasOffsetY - 500
> 
> out_file = laspy.file.File(output_file, mode="w", header=in_file.header)
> out_file.points = allPoints
> out_file.close()
> ```

@zwnk 
Thank you very much for nice reply. According to my question your answer is OK.
But for my case, after extracting x, y, and z, 
I processed x, y, z separately. Such as filtering, smoothing, etc.

In this situation, how can write the x, y, z?

**Comment by zwnk** [comment]
i updated the code block, i missed the important part when i was copy and pasting from my code.
It should also be written within the laspy documentation. Another source can be https://gis.stackexchange.com/

**Comment by ibrahimLearning** [comment]
> i updated the code block, i missed the important part when i was copy and pasting from my code.
> It should also be written within the laspy documentation. Another source can be https://gis.stackexchange.com/

Would you provide specific link please?

**Comment by zwnk** [comment]
there is a link in the readme of the repo ...
don't expect that people are doing your work for you ... 
Make specific questions with a specific code sample ...
