### ISSUE TITLE
Is laspy.file able to read Range data from .laz file?

### ISSUE THREAD

**Issue by xleEmesent** [laspy/laspy#130]
Hi, All. Does laspy.file has a function to read Range data from .laz file.
```
import laspy.file as File
inFile = File.File('xyz.laz',mode='r')
inFile.inFile.range
```
Then the following error generated: 
```
laspy.util.LaspyException: Dimension: range not found. Existing dimensions: X, Y, Z, intensity, flag_byte, raw_classification, scan_angle_rank, user_data, pt_src_id, gps_time, Range, Ring
```
Has the function of reading Range data not been implemented yet or there is another function to extract the Range data?

Thanks.

**Comment by mk-a** [comment]
Hi,
Can you try to access the dimension using the following ? 
`inFile.reader.get_dimension("Range")`

I am having a similar issue. I used PDAL's Eigenvalues filter, that writes the result in the extra dimensions : `Eigenvalue0`, `Eigenvalue1`, `Eigenvalue2`.
When I read the file with laspy and I try  `inFile.eigenvalue0`  i get the following :

```
LaspyException: Dimension: eigenvalue0 not found. Existing dimensions: X, Y, Z, intensity, flag_byte, raw_classification, scan_angle_rank, user_data, pt_src_id, gps_time, red, green, blue, Eigenvalue0, Eigenvalue1, Eigenvalue2
```

And when I try `inFile.Eigenvalue0` I get : `AttributeError: 'File' object has no attribute 'Eigenvalue0'`

However, I can access it using `inFile.reader.get_dimension("Eigenvalue0")` which is not very convenient.

**Comment by xleEmesent** [comment]
@mk-a , Yes, it works now using inFile.reader.get_dimension("Range"). Thanks!!!
But If tried with 'ReturnNumber' as following:
```
inFile.ReturnNumber
rts = inFile.reader.get_dimension("ReturnNumber")
```
Error generated as following:
```
laspy.util.LaspyException: Dimension: ReturnNumber not found. Existing dimensions: X, Y, Z, intensity, flag_byte, raw_classification, scan_angle_rank, user_data, pt_src_id, gps_time, Ring, Range

```

Do you have any suggestion for reading "ReturnNumber" as well? Thanks.

**Comment by mk-a** [comment]
`inFile.return_num` works for me.

**Comment by xleEmesent** [comment]
@mk-a, thanks for you reply. My last question is: if I have additional extra dimensions whose names are unknown in an input file.  Is there anyway I can get access to those extra dimensions names 'xxx' in Laspy, then I can use 
```
inFile.reader.get_dimension("xxx")
```

The question is very similar to "extra dimensions : Eigenvalue0, Eigenvalue1, Eigenvalue2." in your case, except you know the names of the dimension. Thanks.

**Comment by xleEmesent** [comment]
@mk-a  I think I found the answer by myself, the exception message prints out all the dimensions name. Many Thanks!!!.

**Comment by xleEmesent** [comment]
@mk-a or use "inFile.point_format.lookup.keys()" to print all dimension names.

**Comment by mk-a** [comment]
You're welcome !

**Comment by xleEmesent** [comment]
@mk-a , I have an additional question to ask about saving a custom defined dimension from pandas data frame to a laspy file (.las) in python.

The code snippet is below:
```
    cols = ['X','Y','Z','I2']
    
    data = {'X': [1,2,3,4,5], 
            'Y':[11,12,13,14,15],
            'Z':[21,22,23,24,25],
            'I2':[40,20,72,82,5]}
    
    df = pd.DataFrame(data=data,columns=cols)
    print(df)
    
    
    hdr = laspy.header.Header()
    outFile = laspy.file.File("example1.las", mode="w", header=hdr)
    
    namesOutput = [i.name for i in outFile.point_format]
    
    for col in df.columns:
        if (col in namesOutput) == False:
                outFile.define_new_dimension(name = col,data_type = 9, description = col)
        outFile.writer.set_dimension(col, df[col].values)

```

The error message I got is below:
```
    outFile.define_new_dimension(name = col,data_type = 9, description = col)
  File "/home/xuesong/emPjs/markerBand_env/lib/python3.7/site-packages/laspy/file.py", line 179, in define_new_dimension
    self._writer.define_new_dimension(name, data_type, description)
  File "/home/xuesong/emPjs/markerBand_env/lib/python3.7/site-packages/laspy/base.py", line 1205, in define_new_dimension
    raise laspy.util.LaspyException("New dimensions may be defined only for write mode files which do not yet possess point records.")
laspy.util.LaspyException: New dimensions may be defined only for write mode files which do not yet possess point records.
```

Would you kindly shed some light on this issue?

Regards

**Comment by grantbrown** [comment]
When you hit "set_dimension", that kicks off a chain of events to make sure the file is appropriately sized and padded. Then, the next time you try to define a dimension you get that error because the file now has point records. 

Now, laspy could certainly support dealing with this case transparently, but it would involve a lot of byte moving for large files. You should be able to get around the issue by defining all new dimensions first, then assigning them data. 

With that being said, I don't think you want to define dimensions X,Y,and Z...

**Comment by xleEmesent** [comment]
@grantbrown , Thanks. I think I worked it out this way. Correct me if it is still an issue.

```
    cols = ['X','Y','Z','I2']
    
    data = {'X': [1,2,3,4,5], 
            'Y':[11,12,13,14,15],
            'Z':[21,22,23,24,25],
            'I2':[40,20,72,82,5]}
    
    df = pd.DataFrame(data=data,columns=cols)
    print(df)
    
    
    hdr = laspy.header.Header()
    outFile = laspy.file.File("example1.las", mode="w", header=hdr)
    
    namesOutput = [i.name for i in outFile.point_format]
    
    for col in df.columns:
        if (col in namesOutput) == False:
                outFile.define_new_dimension(name = col,data_type = 9, description = col)
   
    for col in df.columns:
        outFile.writer.set_dimension(col, df[col].values)
```
