### ISSUE TITLE
add points into existed las files without loading all points into memory

### ISSUE THREAD

**Issue by Crear12** [laspy/laspy#131]
Hi,
I'm working on some very big las files, which exceed the total RAM (32GB) on my laptop. Although we have a 128GB server in our lab but I still prefer to writing more points into SSD/HDD directly rather than loading all the points in RAM, adding the new point, and then writing into drives again. 
Is there a function to do that? Like, inFile.points.append(((1002994, 7866044, 1492324, 47545, 73, 0, 0, 0, 1, 53970, 46260, 39064),))

**Comment by hobu** [comment]
> I'm working on some very big las files, which exceed the total RAM (32GB) on my laptop. 

It is unreasonable to expect this to work out of the box. Either make a big swap file, or learn how to use [FIFO](https://man7.org/linux/man-pages/man7/fifo.7.html)

**Comment by zwnk** [comment]
another approach would be to cut you data into tiles before processing. this way you could also process multiple tiles at once.
