### ISSUE TITLE
Extra dimensions case sensitivity

### ISSUE THREAD

**Issue by luisenview** [laspy/laspy#140]
Hey,

I think this commit https://github.com/laspy/laspy/commit/c97ffa521f158db73a2fe1651648a7488912ffdc has caused an inconsistency in laspy/laspy/file.py. 

The problem starts by adding extra dimensions as attributes to the File class with self.addProperty(). Here for example: https://github.com/laspy/laspy/blob/ac0b47aae3b1409c57aaaeaed049b3a09fa70f7a/laspy/file.py#L88
As you see, we're still lower()-ing the name of the dimension loaded to the file object, even though the property originally in the laz/las file could be Caps.

The outcome of this is that if you have dimensions in the las/laz file with Caps, like `ThisDim`, then when it gets added as attribute to the File class, they'll end up like `file.thisdim`. That's not necessarily a problem per se, but, when you're accessing FileManager here: https://github.com/laspy/laspy/blob/ac0b47aae3b1409c57aaaeaed049b3a09fa70f7a/laspy/base.py#L722
... the lookup returns is still in caps, since we lowered the requirements in the PR, and the list returned to check dimensions will be `ThisDim`, which in effect prevents the dimension from being accessed in any way from the File object.

I think the quick and dirty solution is to remove the .lower() from all the `dimension.name.decode().replace("\x00", "").replace(" ", "_").lower()`'s and allow attributes to be case sensitive. I've tried this locally and the fix seems to work fine. 

I tried to put a PR/branch, with this, but I'm getting a access denied, hence the bug report.

Let me know if this doesn't make any sense or needs some clarification.

Thanks!

Luis

**Comment by kbevers** [comment]
I believe you are correct in this. It would be nice to see a pull request with all the changes and possibly a new test to the test suite to check that it works (if the existing tests doesn't cover this, that is).

> I tried to put a PR/branch, with this, but I'm getting a access denied, hence the bug report.

You need to fork the repository first, then create a branch on your personal fork of Laspy. Pull requests can then be based on bBranches from your fork.

**Comment by grantbrown** [comment]
Agreed, sorry for the oversight

**Comment by luisenview** [comment]
Ok!, I have already the fix, I'll add some tests.
