### ISSUE TITLE
Merge with pylas's internals to only provide one Python LAS API?

### ISSUE THREAD

**Issue by hobu** [laspy/laspy#141]
@tmontaigu built the [pylas](https://github.com/tmontaigu/pylas) library to provide better LAZ support and modernize the internals of the library. The challenge of trying to modernize laspy's internals might have looked to be a tall mountain to climb, but now we have two Python APIs with similar names and APIs that do similar (if not equal) things.

I would very much support giving Thomas commit rights to refactor laspy's internals to match what he's done with pylas so the effort forks could merge back together. I think laspy is mostly concerned about preserving its external, high level APIs, and it is not wed to how its internals work. If they could be modernized to follow pylas' hinting and other approaches that simplify things significantly and improve performance in the process, I think everyone would see it as a win.

What do you think @kbevers and @grantbrown?

**Comment by grantbrown** [comment]
Sounds reasonable to me, no objection.

**Comment by kbevers** [comment]
Yeah, it's a go from me as well.

**Comment by hobu** [comment]
@grantbrown please add @tmontaigu to the org and the committers list.

**Comment by grantbrown** [comment]
Done. Also promoted you to owner, I don't want to be the weak link.

**Comment by hobu** [comment]
@tmontaigu please write a new ticket with your plan when you get the opportunity. You should have credentials to make a new branch and start work as time allows.
