### ISSUE TITLE
Can I join 2 point cloud las files with laspy?

### ISSUE THREAD

**Issue by krishnaap** [laspy/laspy#145]
Can I join 2 point cloud las files with laspy?

**Comment by shay-sommerfield** [comment]
Yes you can. Here is an [example about creating a las file from scratch](https://laspy.readthedocs.io/en/latest/examples.html#creating-from-scratch). However, instead of using dummy data, you would pull the data out of the two files you would concatenate the numpy data within each. You will also need to decide what data from each header you want to keep as well as pass the appropriate VLRs (global encoding data and custom data that isn't part of a standard las file.

**Comment by Janphr** [comment]
I try to do the same. 
I extract the xyz points and concatenate them to the other points. They already have the correct values.
After that I do the steps 1 and 2 of the example [Creating a new LasData](https://laspy.readthedocs.io/en/latest/examples.html#creating-from-scratch)
but for some reason, with or without adding the offset, all point clouds share the same bounds:
![image](https://user-images.githubusercontent.com/45623010/171253222-985c8e85-ecdd-46b2-8c73-1c15dfd008be.png)


Header of first sub cloud:
![image](https://user-images.githubusercontent.com/45623010/171258336-144d409d-3342-496e-a6e5-92a9b54071c9.png)

Header of merged point cloud:
![image](https://user-images.githubusercontent.com/45623010/171258251-67ec4d0d-29a2-46d6-876c-01527e8ac272.png)

Header of the last sub cloud:
![image](https://user-images.githubusercontent.com/45623010/171258556-50134751-b9c7-491e-996a-1fc87a6a6919.png)

Everything seems fine, right? I don't understand how the point coordinate information gets lost. 

```
def merge(src_dir='las_clouds', out_las='test.las', delete_after_finish=False):
    pt_count = 0

    for (dir_path, dir_names, file_names) in os.walk(src_dir):
        for file_name in file_names:
            in_las = os.path.join(dir_path, file_name)
            with laspy.open(in_las) as f_in:
                # header.offsets = np.min(np.vstack((header.offsets, f_in.header.offsets)), axis=0)
                pt_count += f_in.header.point_count


    xyz = np.zeros((pt_count, 3))
    idx = 0
    for (dir_path, dir_names, file_names) in os.walk(src_dir):
        for file_name in file_names:
            in_las = os.path.join(dir_path, file_name)
            f_in = laspy.read(in_las)
            xyz[idx:idx + f_in.header.point_count] = f_in.xyz
            idx += f_in.header.point_count

            if delete_after_finish:
                os.remove(in_las)

    min_xyz = np.min(xyz, axis=0)
    max_xyz = np.max(xyz, axis=0)

    header = laspy.LasHeader(point_format=3, version="1.2")
    header.offsets = np.min(xyz, axis=0)
    header.scales = np.array([0.1, 0.1, 0.1])

    las = laspy.LasData(header)

    las.x = xyz[:, 0]
    las.y = xyz[:, 1]
    las.z = xyz[:, 2]

    las.write('{}{}'.format(las_path, out_las))
```
