### ISSUE TITLE
Tests not included in PyPI release

### ISSUE THREAD

**Issue by plimkilde** [laspy/laspy#147]
Laspy 2.0.0 no longer distributes tests with its PyPI package, meaning that it is not directly testable when we package it for conda-forge (the feedstock draws upon the PyPI release, see discussion at [laspy-feedstock#5](https://github.com/conda-forge/laspy-feedstock/pull/5)). Should the tests be added back into the PyPI package?

**Comment by tmontaigu** [comment]
I did not think that there was a use for tests being packaged with the Pypi source distribution.

I will add them back in the Pypi package

**Comment by tmontaigu** [comment]
I guess a new release is needed for you to be able to try ?

**Comment by plimkilde** [comment]
I suppose a new release will be needed, yes. And thank you very much for the fast response :-)
