### ISSUE TITLE
Merging multiple las files into a single las file doesn't seem to take into account the offset.

### ISSUE THREAD

**Issue by arknoll** [laspy/laspy#150]
I have 50 las files that I'm using laspy to merge into a single las file like this:

```
for lasFile in lasFiles:
        with laspy.open(lasFile) as input_las:
            if os.path.exists(merged_file):
                with laspy.open(merged_file, mode="a") as merged_las:
                    merged_las.append_points(input_las.points)
            else:
                with laspy.open(merged_file, mode="w", header=input_las.header) as merged_las:
                    merged_las.write_points(input_las.points)
```

The merged las file appears to not take into account the offset from all the various merged files.
![image](https://user-images.githubusercontent.com/1660183/124823630-0c732480-df37-11eb-9a47-65e2a4c96d57.png)
![image](https://user-images.githubusercontent.com/1660183/124823660-16952300-df37-11eb-843f-c3ce1b975fc0.png)

Do I need to manually get all the points into the same offset before appending the points?

**Comment by tmontaigu** [comment]
Yes that's the idea.

 `LasData` object (obtained from `laspy.read` for example) have a `change_scaling` method that is meant to do that
however there was a small typo in the function which made it incorrect it is fixed on master, but 2.0.1 is till bugged in that regard.

Also i found that the append_points for LAZ files produces an incorrect file that other readers like PDAL can't read (but LAS works) I'll investiguate this.

**Comment by tmontaigu** [comment]
the new release (2.0.2) should now have function to make it easy the re-scale/re-offset points, as well as the fix for LAZ appending

**Comment by deeplook** [comment]
Is there an example or test for this feature? Is it related to the `LasAppender` and `LazrsAppender` classes?

**Comment by tmontaigu** [comment]
https://laspy.readthedocs.io/en/latest/api/laspy.point.record.html?highlight=change_scaling#laspy.point.record.ScaleAwarePointRecord.change_scaling

https://laspy.readthedocs.io/en/latest/api/laspy.lasdata.html?highlight=change_scaling#laspy.lasdata.LasData.change_scaling

**Comment by miniygq** [comment]
how to use [change_scaling](https://laspy.readthedocs.io/en/latest/api/laspy.lasdata.html?highlight=change_scaling#laspy.lasdata.LasData.change_scaling)
