### ISSUE TITLE
Laspy does not write all scalar fields

### ISSUE THREAD

**Issue by chrise96** [laspy/laspy#151]
I have a *.laz file with xyzrgb fields and the scalar fields “number of returns” and “return number”. When reading the scalar field of the file with `print(las.return_number)`, I get the following output:
`<SubFieldView([1 1 2 ... 1 1 1])>`

When saving the contents of the file locally and read it again I get an empty scalar field back as output:
` <SubFieldView([0 0 0 ... 0 0 0])>`
 
   Is this a bug or do I need to add an extra step when writing (or reading) a *.laz file?

**Comment by tmontaigu** [comment]
It is most likely a bug as you don't have to do extra step to write all the scalarfields.

However I cannot reproduce it with this sample code:
```Python
import laspy

las = laspy.read(r"some_file.laz")
las.return_number[2] = 2
print(las.return_number)
# <SubFieldView([1 1 2 ... 1 1 1])>

las.write('tmp.laz')
las2 = laspy.read("tmp.laz")
print(las2.return_number)
# <SubFieldView([1 1 2 ... 1 1 1])>
```

Can you share what you are doing ?

**Comment by chrise96** [comment]
Ah now I see! I created a new las file using `laspy.LasData(las.header)` and `las2.points = las.points `. But, forgot to also add `las2.return_number = las.return_number`. Thank you. Will close this issue now 👍

**Comment by tmontaigu** [comment]
🤔 
you don't need to do `las2.return_number = las.return_number` after you've done `las2.points = las.points`

```Python
import numpy as np
import laspy

las = laspy.read("some.laz")
las.return_number[:] = 6
assert np.all(las.return_number == 6)

las2 = laspy.LasData(header=las.header)
assert np.all(las2.return_number == 0)
las2.points = las.points
assert np.all(las2.return_number == 6)

las2.write('tmp.laz')
las3 = laspy.read('tmp.laz')
assert np.all(las3.return_number == 6)
```

**Comment by chrise96** [comment]
My bad… I looked at an old laz file that was generated using the other library pylas. So, it is a bug in **pylas** and not **laspy**.

FYI this is the code I used with pylas:

```
import pylas

las = pylas.read(in_file)

las2 = pylas.create(point_format_id=las.header.point_format_id)
las2.points = las.points
print(las2.return_number)
las2.add_extra_dim(name="label", type="uint16",
                   description="Labels")
las2.write('tmp.las')
las3 = pylas.read('tmp.las')
print(las3.return_number)
```
