### ISSUE TITLE
Conda Install via conda-forge - Update docs to mention conda install and limitations?

### ISSUE THREAD

**Issue by SuaveFool** [laspy/laspy#153]
There is still a laspy build actively updated for conda-forge, which includes the latest versions of laspy, but only the laszip dependency for LAZ support is available (i.e. lazrs is not available through conda-forge).

It may be worth updating the docs to say that laspy is available with conda via conda-forge, and whether this is actually supported or not:
`conda install -c conda-forge laspy`
and optionally with the laszip package for LAZ support:
`conda install -c conda-forge laspy laszip`

**Comment by tmontaigu** [comment]
If I'm correct, the laszip that is available on conda only include the c++ library, and not the Python bindings, so
installing `conda install -c conda-forge laspy laszip` won't give you a `laspy` installation that is LAZ capable.

**Comment by plimkilde** [comment]
Yes, the `laszip` package on conda-forge does not include Python bindings. Laspy 1.x did support LAZ files, by piping the contents through the "laszip" executable provided by the `lastools` package.

That said, it would make good sense to package `laszip-python`/`lazrs`/`lazrs-python` for conda-forge so that they could be used with Laspy 2.0. New feedstocks can be requested on by filing an issue on [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes) or created by following the instructions there.

**Comment by SuaveFool** [comment]
Thanks, @tmontaigu @plimkilde, I missed that gap with laszip-python, I'm not suggesting that you need to support conda installs, but given there is an up to date conda-forge build available, it would be good to either state that this is not currently supported, or call out that laspy is not available with LAZ support via conda-forge because the laszip-python/lazrs/lazrs-python packages are not available. 
I understand that the existing conda build has just carried over from laspy 1.X, and don't have any experience with getting the recipe's working to offer to support, let alone working with the rust tool chain for lazrs.

**Comment by tmontaigu** [comment]
For now, we will just mention conda installation and limitations in the docs.

267e0775d84fe60f375280072e6d5865e5c821a0

**Comment by peterwjacko** [comment]
I realise this is an old (and closed) issue but I want to add this note for others in the future:

`lazrs-python` is now available on conda-forge and enables laspy to read laz files no problem.

`mamba install -c conda-forge lazrs-python`

I was reading laz files in just a few seconds!

**Comment by SuaveFool** [comment]
@peterwjacko thanks! This is good to know, I can remove my last pip dependency from my environment.
