### ISSUE TITLE
GeoTiffKeys parser, error if GeoKeysAscii or GeoKeysDouble ommitted

### ISSUE THREAD

**Issue by SuaveFool** [laspy/laspy#154]
In `laspy.vlrs.geotiff.parse_geo_tiff_keys_from_vlrs()`, it accesses the element 0 of the GeoDoubleParams and GeoAsciiParams, which are optional, and only required if any of the keys in the GeoKeysDirectory have a non-zero TiffTagLocation, according to the LAS 1.2 specification: [LAS 1.2 Specification](https://www.asprs.org/a/society/committees/standards/asprs_las_format_v12.pdf [page: 11, paragraph 2].

This causes errors if reading a LAS file that say has GeoKeysDirectory, and GeoAsciiParams but not GeoDoubleParams.

**Comment by tmontaigu** [comment]
Yes you are right, 434e0cb0de64e1bcdd4fb644d305fef23b8a6694 should fix that
