### ISSUE TITLE
How to create a new las file the same as original las file but with different x, y, z using laspy?

### ISSUE THREAD

**Issue by Martin20494** [laspy/laspy#155]
Hi team

Thank you very much for this great library. I am using it for my project and have some issue as below. Please help me with some of your ideas or advices.

I used laspy to open the las file and did some manipulation on the x, y, z. Now I want to create a new las file with everything the same as the original file except the x, y, z (with the new x, y, z). However, I cannot find the way. I tried the "rw" but always have the error "ValueError: buffer size must be a multiple of element size". I also tried "w", but I did not know how to copy all the characteristics (including spatial reference, srs, tiles, ...) to the new las file. I am using laspy version 1.7.0.

Please help me with this one!

Thank you very much!

Kind regards

Martin Nguyen

**Comment by tmontaigu** [comment]
I cannot really help you for laspy 1.7.

However, with laspy 2.0 it should be easy

**Comment by Martin20494** [comment]
If its laspy 2.0. How will you do it?

kind regards

**Comment by tmontaigu** [comment]
Something like 

```Python
import laspy

las = laspy.read('somefile.las')

las.x = ...
las.y = ...
las.z = ...

las.write('modified.las')
```
