### ISSUE TITLE
How to filter points without loading the entire point cloud into memory

### ISSUE THREAD

**Issue by digital-idiot** [laspy/laspy#156]
I want to filter and read only the filtered portion into the memory instead to loading the entire point cloud and the filtering manually.
For example: I want to read points satisfying the condition:
```python
(x_min < pc.x < x_max) and (y_min < pc.y < y_max) 
```
How to do this without loading the entire point cloud into memory?

For contrast:
In [readLAS](https://rdrr.io/cran/lidR/man/readLAS.html) `R` package there are two argument `select` and `filter` in `read` method in order to filter points as well as to load subset of attributes.

**Comment by tmontaigu** [comment]
There is no function that does that kind of filtering automatically, so you have to do it manually. If you cannot afford to 
read all the points in memory, you have to use chunked reading.

```Python
import numpy as np

import laspy

with laspy.open("tests/data/simple.las") as f:
    print(f.header.point_count)
    all_points = laspy.PackedPointRecord.empty(f.header.point_format)

    for points in f.chunk_iterator(50):
        points = points[points.classification == 2]
        all_points.array = np.append(all_points.array, points.array)

    las = laspy.LasData(header=f.header, points=all_points)


print(las.classification)
```

**Comment by digital-idiot** [comment]
> There is no function that does that kind of filtering automatically, so you have to do it manually. If you cannot afford to
read all the points in memory, you have to use chunked reading.

I see. Thank you.
