### ISSUE TITLE
Buffer size error when adding a new dimension

### ISSUE THREAD

**Issue by pasc85** [laspy/laspy#160]
Hi laspy Team!

I'm having a hard time adding a new dimension to a las dataset. I'm using laspy 2.0.3 (build pyh8a188c0_0). Here's my code:

```python
import laspy
import numpy as np
from copy import deepcopy
```
```python
filename = "data/scan001"
dtype = np.uint32

expansion_dict = {'name': 'new_dim',
                  'type': dtype,
                  'description': "a new dimension"}

with laspy.open(f"{filename}.las") as input_las_data:
    
    hdr = deepcopy(input_las_data.header)
    hdr.add_extra_dim(laspy.ExtraBytesParams(**expansion_dict))
    
    with laspy.open(f"{filename}_augmentation_dev.las", mode="w", header=hdr) as output_las_data:
        
        points = input_las_data.read_points(-1).copy()
        print("Before add_extra_dim:", points.point_format)
        points.point_format.add_extra_dimension(laspy.ExtraBytesParams(**expansion_dict))
        print("After add_extra_dim:", points.point_format)
        
        new_column = np.arange(points.memoryview().shape[0], dtype=dtype)
        
        #setattr(points, 'new_dim', new_column)
        #points['new_dim'] = new_column
        points.new_dim = new_column
        
        output_las_data.write_points(points)
```
```python
l1 = laspy.read(f"{filename}.las")
l2 = laspy.read(f"{filename}_augmentation_dev.las")
```

The main block of code (second block) seems to work, but when loading the newly written dataset (third block) I get an `ValueError: buffer size must be a multiple of element size` (for `l2`). It is actually possible to load the new file in CloudCompare, but the points got mixed up.

(You'll notice that I have three options there for assigning values to the new dimension -- as I was trying different approaches, I found myself in situations where one of those options would work but the other two would not. E.g. when editing `https://laspy.readthedocs.io/en/latest/examples.html#using-laswriter` to include a new dimension, I needed the `[]` option as the newly written column didn't persist with the `.` option. This may not be an issue and I don't want to post too much code here at once -- I'm sure there's some underlying pattern here that I just haven't understood yet, but do let me know if you'd like to see that other example.)

Coming back to the code above, any thoughts on what I am doing wrong here? What's that buffer size error? Any advice would be greatly appreciated. 

Cheers,
 --Pascal

**Comment by tmontaigu** [comment]
You are trying to reach a bit too close the internals, adding a extra dimension is easier than that.
https://laspy.readthedocs.io/en/latest/lessbasic.html#extra-dimensions

```Python
# When you laspy.read a file, all the data is in memory, so if you modify it
# the actual file won't be modified unless you overwrite it using 'write'
l1 = laspy.read(f"{filename}.las")
l1.add_extra_dim(laspy.ExtraBytesParams(**expansion_dict))
l1.write(f"{filename}_augmentation_dev.las")
print(l1.new_dim)

l2 = laspy.read(f"{filename}_augmentation_dev.las")
print(l2.new_dim)
```

**Comment by pasc85** [comment]
Thanks for the quick response. The reason I had adapted the more complicated structure above is that I thought I needed to do the adding of a new dimension alongside chunking. The code I wrote for that errored with chunking turned off as well as with it turned on, so I posted the non-chunked version of the code here to remove extra layers. I realised though that I may be able to get away without chunking in my use case, so, I'll use the solution you posted for now. Thank you.

**Comment by tmontaigu** [comment]
To do the same thing using chunking the second block would be:

```Python
with laspy.open(f"{filename}.las") as input_las_data:
    hdr = deepcopy(input_las_data.header)
    hdr.add_extra_dim(laspy.ExtraBytesParams(**expansion_dict))

    chunk_size = 1_000_000
    output_points = laspy.ScaleAwarePointRecord.zeros(chunk_size, header=hdr)

    with laspy.open(f"{filename}_augmentation_dev.las", mode="w", header=hdr) as output_las_data:
        for points in input_las_data.chunk_iterator(chunk_size):
            output_points.copy_fields_from(points)
            output_las_data.write_points(output_points)

```

**Comment by pasc85** [comment]
Great, thank you!
