### ISSUE TITLE
Adding extra dimensions to existing LAS yields "bytes too long error"

### ISSUE THREAD

**Issue by CharlesGaydon** [laspy/laspy#164]
Hi,
I read a LAS file, and try to add a float extra dimension (laspy version: 2.0.3);
```
import laspy
import numpy as np
filepath = "../data/lidar_toy/train/845000_6610000.las"
las = laspy.read(filepath)
param = laspy.ExtraBytesParams(name="building_logit", type=float)
las.add_extra_dim(param)
```
When I do this in an isolated script/notebook, everything goes fine and I get the following:
![image](https://user-images.githubusercontent.com/11660435/135872975-21080e88-4fbc-425f-ab15-b843ed3d2319.png)

But the same code in a larger code base yields the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/CGaydon/anaconda3/envs/validation_module/lib/python3.9/site-packages/laspy/lasdata.py", line 125, in add_extra_dim
    self.add_extra_dims([params])
  File "/home/CGaydon/anaconda3/envs/validation_module/lib/python3.9/site-packages/laspy/lasdata.py", line 135, in add_extra_dims
    self.header.add_extra_dims(params)
  File "/home/CGaydon/anaconda3/envs/validation_module/lib/python3.9/site-packages/laspy/header.py", line 396, in add_extra_dims
    self._sync_extra_bytes_vlr()
  File "/home/CGaydon/anaconda3/envs/validation_module/lib/python3.9/site-packages/laspy/header.py", line 736, in _sync_extra_bytes_vlr
    eb_struct = ExtraBytesStruct(
ValueError: bytes too long (57, maximum length 32)
```
I am in debug mode in VS Code, and showing the las in my debug console right after the error, I get this:

![image](https://user-images.githubusercontent.com/11660435/135873773-c47d1583-46aa-4b4f-8627-fa7519d36e59.png)

But if I show it again in the console, the bytes of extra dims are unexpectedly incremented everytime I press "enter", up to high numbers :

![image](https://user-images.githubusercontent.com/11660435/135873564-41ea7618-e0fb-448f-bf8a-a942cbe1cceb.png)
This happens whether I "show" (or print, or any call I am guessing) the LAS data object before or after the calling the error-giving `add_extra_dim`. It really puzzles me that calling the LAS object alterates it. I am guessing that the LAS is accidentally altered which in turn results in no more room for an extra dimension.

Finally, if I replace `las = laspy.read(filepath)` with `las = laspy.create()` (in both isolated script and larger codebase contexts), everything works as expected (no unwanted alteration, no error). 

Am I doing something wrong? Could that have something to do with the specific file I am using? Is there a way to prevent this unwanted effect?

**Comment by tmontaigu** [comment]
Could you share more on what you are doing with the las object  in the larger code base ?

**Comment by CharlesGaydon** [comment]
The error occurs right after loading the las with `laspy.read`, so in theory the LAS is not modified in any way before adding the extra dimension.
But here is the context : 
- These operations are performed as part of a class method, which is supposed to be called several times
- I do smthing like `self.my_las = laspy.load(filepath)`
- Afterwards, the las should be modified eveytime the method is called... but the error occurs at first call.

**Comment by tmontaigu** [comment]
Well, that's not enough for me to reproduce the problem, and if I can't reproduce it I won't be able to fix it.

Does it happen with any file ?

**Comment by tmontaigu** [comment]
The only thing I know is that this error means that the name (or description) of one of the extra dimension exceeds the 32 bytes limits.

**Comment by CharlesGaydon** [comment]
Sorry for the lack of context, I realize this is not enough.

Strangely though, I managed to find what caused the error and remove, although I do not understand how it caused it.

I had the following situation :
- There was a doubled slash in my filepath: `path/to/data//lidar_toy/train/845000_6610000.las`
- This would not cause any issue when calling the following (the file was still read as expected):
```python
as = laspy.read(filepath)
param = laspy.ExtraBytesParams(name="building_logit", type=float)
las.add_extra_dim(param)
```
- But would yield the error when calling
```python
self.my_las = laspy.read(filepath)
param = laspy.ExtraBytesParams(name="building_logit", type=float)
self.my_las.add_extra_dim(param)  # error occurs here
```
Removing the double slash removed the error.

And as for the incrementing "extra_bytes", it seems it was linked to my debugging console (still unexplainable though), but printing did not show this behavior at run time.

Sorry for the somewhat obscure bug report! Thanks for your answers, I am closing since it is probably an isolated, env specific issue.

**Comment by tmontaigu** [comment]
That's strange 🤔 

But if you made it works it ok I guess
