### ISSUE TITLE
Writing file without updating header

### ISSUE THREAD

**Issue by kcotar** [laspy/laspy#177]
I have a use-case where I do not want to update header information as it messes with bounding box info that is in our case larger than would be computed from the actual point cloud. It needs to stay as it is - expected by the tertiary software.

I have created a short custom fix for that - see linked PR.

**Comment by tmontaigu** [comment]
hmm 🤔  so you need to be able to write a file with an incorrect header

**Comment by kcotar** [comment]
Yes and no. Yes as mins/maxs bounds are larger than actual data span and no as I am only modifying classification values in las produced by another software and header needs to stay as it was.

I know this is probably not a standard application and need some extra care, therefore I will use my fork for this.
