### ISSUE TITLE
How to delete a field that was added with add_extra_dim?

### ISSUE THREAD

**Issue by CharlesGaydon** [laspy/laspy#179]
Hi, this should be fairly simple: I created an extra dim with something like the following:
```
coln = "new_field"
param = laspy.ExtraBytesParams(name=coln, type=int)
las_data.add_extra_dim(param)
las_data[coln][:] = 0
```
Now I need to delete the new field. Is there a way to do so? I tried `del las.new_field` and `del las["new_field"]` without success. And there is nothing about it in [LasData doc](https://laspy.readthedocs.io/en/latest/_modules/laspy/lasdata.html#LasData).
Thanks!

**Comment by tmontaigu** [comment]
Yes this is not possible at the moment

**Comment by CharlesGaydon** [comment]
Surprising. Thanks for the confirmation.

**Comment by tmontaigu** [comment]
Re opening at it makes sense to implement this sometime
