### ISSUE TITLE
Laspy corrupts las file when adding classification data

### ISSUE THREAD

**Issue by lc-guy** [laspy/laspy#180]
I have a 50k point LAS file I'm trying to assign values to.

```python
    point_cloud=lp.read(filelas)
    labels=np.load(filenpy)

    point_cloud.classification = labels

    filelas_new = filelas.parent / (filelas.stem + '_classified' + filelas.suffix)
    point_cloud.write(filelas_new)
```
Original labels:
```
(Pdb) labels
array([4, 6, 7, ..., 0, 4, 6])
```

Reading the written labels with laspy:
```
(Pdb) lp.read(filelas_new).classification
<SubFieldView([4 6 7 ... 0 4 6])>
```

Reading the labels as exported with pdal:
```
>>> result = np.genfromtxt(csv_export)
>>> result
array([  4.,   6.,   7., ...,  96., 100., 102.])
```
Uh-oh.

Reading the actual points from the cli:
```
$ pdal info <file>.las -p 48127
{
     [...]
      "Classification": 1,
     [...]
}
$ pdal info <file>.las -p 48128
{
    [...]
      "Classification": 164,
    [...]
}
```

All points after 48128 have 160 added to their classification value, and all points after 49650 have 96 added instead.
Could be either a pdal or a laspy issue, I'm not sure which it is... but banking on laspy for now.
laspy still correctly reads the points it wrote itself, for what it's worth.

Metadata info:
```
{
  "filename": "<file>.las",
  "metadata":
  {
    "comp_spatialreference": "",
    "compressed": false,
    "count": 50000,
    "creation_doy": 340,
    "creation_year": 2021,
    "dataformat_id": 3,
    "dataoffset": 227,
    "filesource_id": 0,
    "global_encoding": 0,
    "global_encoding_base64": "AAA=",
    "header_size": 227,
    "major_version": 1,
    "maxx": 1089475.634,
    "maxy": 8902601.796,
    "maxz": 2147411.689,
    "minor_version": 2,
    "minx": -1058688.202,
    "miny": 4972307.306,
    "minz": -2033660.413,
    "offset_x": 602300,
    "offset_y": 7066500,
    "offset_z": -41.8194823965444,
    "point_length": 34,
    "project_id": "00000000-0000-0000-0000-000000000000",
    "scale_x": 0.001,
    "scale_y": 0.001,
    "scale_z": 0.001,
    "software_id": "",
    "spatialreference": "",
    "srs":
    {
      "compoundwkt": "",
      "horizontal": "",
      "isgeocentric": false,
      "isgeographic": false,
      "prettycompoundwkt": "",
      "prettywkt": "",
      "proj4": "",
      "units":
      {
        "horizontal": "unknown",
        "vertical": ""
      },
      "vertical": "",
      "wkt": ""
    },
    "system_id": ""
  },
  "pdal_version": "2.0.1 (git-version: Release)"
}
```

Thanks in advance for your help.

**Comment by tmontaigu** [comment]
This is very probably a problem of PDAL.

For LAS files with point format (or  "dataformat_id" in PDAL) {0, 1, 2, 3, 4, 5} the specification says that the classification is stored on 5 bits (so 31 is the maximum value) and the 3 bits following it are flags (synthetic, keypoint, withheld). You file has `dataformat_id: 3`.
https://laspy.readthedocs.io/en/latest/intro.html#point-format-0

In laspy the distinction is clear, and each of these fields have their own equivalent in laspy, in PDAL they don't make the distinction and the `classification` bundles everything.

if you do `lp.read(filelas_new).raw_classification` you should see the same values as what PDAL shows you.

**Comment by lc-guy** [comment]
Thanks for the info. Seems like the solution is to convert the las files to 1.4 format before adding the classification data. I'll be updating the related issue on the pdal issue tracker now that I've found it.
