### ISSUE TITLE
change_scaling in ScaleAwarePointRecord changes x, y, z

### ISSUE THREAD

**Issue by LaurensDiels** [laspy/laspy#181]
When writing a script to merge multiple las files with different offsets and scales together, I noticed unexpected behaviour in the change_scaling method in `ScaleAwarePointRecord`. I had expected this would keep `x`, `y`, `z` constant but alter `X`, `Y`, `Z` and of course `scales` and `offsets`. However, this does not seem to be the case.

Digging into the source code I think the `None` check code should change from
```python
    if scales is not None:
        self.scales = scales
    if offsets is not None:
        self.offsets = offsets
```
to
```python
    if scales is None:
        scales = self.scales
    if offsets is None:
        offsets = self.offsets
```

This would also make it the pretty much the same as in `LasData`'s `change_scaling` (which presumably had the same problem until it was fixed in version 2.0.2).

**Comment by tmontaigu** [comment]
Yes this actually makes sense, the current implementation is wrong
