### ISSUE TITLE
How to write RGB data with laspy2

### ISSUE THREAD

**Issue by Rheinwalt** [laspy/laspy#184]
Is RGB not supported yet or am I doing something wrong? I can read RGB values without any problems like that:

```Python
import numpy as np
import laspy as lp

f = lp.read('file.las')
p = np.c_[f.x, f.y, f.z, f.red, f.green, f.blue]

# However, I don't manage to modify p and write it back into a new file. This is what I tried:

header = lp.LasHeader(point_format = 3, version = '1.2')
header.offsets = np.min(p[:, :3], axis=0)
header.scales = np.ones(3) * 0.001
with lp.open('new.las', mode = 'w', header = header) as writer:
    point_record = lp.ScaleAwarePointRecord.zeros(p.shape[0], header = header)
    point_record.x = p[:, 0]
    point_record.y = p[:, 1]
    point_record.z = p[:, 2]
    point_record.red = p[:, 3]
    point_record.green = p[:, 4]
    point_record.blue = p[:, 5]
    writer.write_points(point_record)
```
The x,y,z-part works like a charm, just RGB is the problem. I tried the above with untouched color values in [0, 65535) and also explicitly casting the dtype with p.astype('uint16'). And I also re-scaled to [0, 1) because I thought maybe the ScaleAwarePointRecord class also scales RGB? Would be nice imho ...

I'd appreciate any hints on what I might do wrong.

Best, A.

**Comment by tmontaigu** [comment]
There is an inconsistency within the `ScaleAwarePointRecord` and setting value using `point_record.dimension_name` only works for `x`, `y`, `z`.

So if you wan to use `ScaleAwrePointRecord` for now you have to do
```Python
import numpy as np
import laspy as lp

f = lp.read('file.las')
p = np.c_[f.x, f.y, f.z, f.red, f.green, f.blue]

# However, I don't manage to modify p and write it back into a new file. This is what I tried:

header = lp.LasHeader(point_format = 3, version = '1.2')
header.offsets = np.min(p[:, :3], axis=0)
header.scales = np.ones(3) * 0.001
with lp.open('new.las', mode = 'w', header = header) as writer:
    point_record = lp.ScaleAwarePointRecord.zeros(p.shape[0], header = header)
    point_record['x'] = p[:, 0]
    point_record['y'] = p[:, 1]
    point_record['z'] = p[:, 2]
    point_record['red'] = p[:, 3]
    point_record['green'] = p[:, 4]
    point_record['blue'] = p[:, 5]
    writer.write_points(point_record)
```

Or you can use `LasData`

**Comment by Rheinwalt** [comment]
Yes, that works for me. Thanks! Maybe I should note for others that the ScaleAwarePointRecord does not scale anything regarding colors. You have to ensure that RGB values are between 0 and 65537.
