### ISSUE TITLE
Fails to read laz file, failed to fill whole buffer

### ISSUE THREAD

**Issue by dcolley** [laspy/laspy#187]
I'm trying to read the test.laz from rapidlasso.com's test files.

I installed laspy with `pip install laspy[laszip]`

```bash
python read_test.py
Traceback (most recent call last):
  File "/Users/derek/Sites/python/gis/read_test.py", line 5, in <module>
    las = laspy.read('test.laz')
  File "/Users/derek/miniforge3/lib/python3.9/site-packages/laspy/lib.py", line 173, in read_las
    with open_las(source, closefd=closefd, laz_backend=laz_backend) as reader:
  File "/Users/derek/miniforge3/lib/python3.9/site-packages/laspy/lib.py", line 110, in open_las
    return LasReader(stream, closefd=closefd, laz_backend=laz_backend)
  File "/Users/derek/miniforge3/lib/python3.9/site-packages/laspy/lasreader.py", line 57, in __init__
    self.point_source = self._create_laz_backend(source)
  File "/Users/derek/miniforge3/lib/python3.9/site-packages/laspy/lasreader.py", line 199, in _create_laz_backend
    return LazrsPointReader(source, laszip_vlr, parallel=True)
  File "/Users/derek/miniforge3/lib/python3.9/site-packages/laspy/lasreader.py", line 332, in __init__
    self.decompressor = lazrs.ParLasZipDecompressor(
pylaz.LazrsError: IoError: failed to fill whole buffer
```

`python 3.9.7`

If I decompress the file with [rapidlasso's laszip] `laszip -i test.laz -o test.las` then I can read the .las file...
Is this a problem of the test.laz file I'm using?

[test.laz.zip](https://github.com/laspy/laspy/files/7830447/test.laz.zip)

**Comment by hobu** [comment]
Which file? Some of the LAZ files there are a very old version of LAZ.

**Comment by dcolley** [comment]
The file is added to above comment

**Comment by hobu** [comment]
> Invalid version 1 found in LAZ VLR

Yes, this is a very old LAZ version. Do you have this same problem with other LAZ v1 files or something? Why are you using this particular test file?

**Comment by dcolley** [comment]
I am trying to convert from shp to las... on a Mac. The rapidlasso tools are aimed at Windows, (few of their exes have equivalent linux/mac executables). Anyway, I started with their test file... to see if this would work.

What I really want to do is model mine-shaft/tunnel data (below ground) in 3d [using QGIS?]. I have the shp files from AutoCAD / Datamine - these work on the pc that has a license.

But in QGIS 3d view it's all flat. I expect I'm missing the lidar data.

**Comment by tmontaigu** [comment]
Indeed this is an old LAZ file that uses version 1 of LAZ compression with `point wise` encoding as opposed to the more common `point wise chunked` with version 2, the error is raised in lazrs tho, so you probably did not install with `pip install laspy[laszip]` otherwise laszip would have been used (and laszip i think would support that file)

At least its an easy fix in lazrs
