### ISSUE TITLE
The X properties are no longer automatically updated when setting x in version 2.1.0 (It is in 2.0.3)

### ISSUE THREAD

**Issue by karlHolmquist** [laspy/laspy#189]
Hi, I'm utilizing laspy for creating a .las file from a numpy array, but version 2.1.0 seems to have removed the automatic step in which .X is calculated from .x when doing 'las.x = x'

Issue:
Creating a new lasfile and setting the '.x' property doesn't update the '.X' property properly which leads to incorrect bounding box calculation.

Code for reproduction:
```Python
las = laspy.create(point_format=6, file_version="1.4")
cloud = np.random.randn(100, 3)

# Add xyz information
las.x = cloud[:, 0]
las.y = cloud[:, 0]
las.z = cloud[:, 0]
 
# Write data to file

las.write(fn)
print(las.header.x_min, las.header.x_max)  # Prints correctly in 2.0.3 but is zero for all boundaries in 2.1.0
print(las.x)  # Prints the correct x-values 
print(las.X)  # Prints correctly for version 2.0.3 but is an empty list in 2.1.0
```

Suggested solution:
- Either add an entry in the documentation specifying how to create a new las file from numpy data and ideally add a warning when writing a file if .x and .X missmatches.
- Change the behaviour of 2.1.0 to automatically update .X if .x is set as done previously in version 2.0.3

Thanks for the library

All the best,

**Comment by tmontaigu** [comment]
The version 2.1.1 was release and should contain the fix for this regression
