### ISSUE TITLE
Installing with lazrs does not work

### ISSUE THREAD

**Issue by bmmeijers** [laspy/laspy#192]
When installing laspy with lazrs backend, it fails for me:

$ pip install laspy[lazrs]
Processing /home/martijn/.cache/pip/wheels/d6/0f/cf/83d78374f0e7459a5c3aa357a6d1da22d2aa9d50b03a39e8d2/laspy-2.1.0-py3-none-any.whl
Requirement already satisfied: numpy in ./env/lib/python3.8/site-packages (from laspy[lazrs]) (1.22.1)
ERROR: Could not find a version that satisfies the requirement lazrs<0.5.0,>=0.4.0; extra == "lazrs" (from laspy[lazrs]) (from versions: 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5)
ERROR: No matching distribution found for lazrs<0.5.0,>=0.4.0; extra == "lazrs" (from laspy[lazrs])

Installing lazrs separately works:

$ pip install lazrs
Collecting lazrs
  Downloading lazrs-0.2.5-cp38-cp38-manylinux2010_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 9.1 MB/s 
Installing collected packages: lazrs
Successfully installed lazrs-0.2.5

However, the version indeed does not seem to match with what is required in the setup.py of laspy (lazrs<0.5.0,>=0.4.0).

Do I do something wrong (or does it depend on my system that I do not get the correct version of lazrs)?

**Comment by davidcaron** [comment]
Do you happen to have a version of pip older than 21? What is the output of `pip --version`?
If so, try `pip install -U pip` to upgrade pip and retry.

**Comment by bmmeijers** [comment]
I was at 20.0.2 with pip, upgrading it to pip-21.3.1 it solved the issue! Thanks a lot.
