### ISSUE TITLE
Scaling issue when moving from pylas to laspy2

### ISSUE THREAD

**Issue by jpswensen** [laspy/laspy#199]
Using the same example as my previous issue when we were porting from pylas to laspy2, I am seeing a change in behavior in how scaling is happening.

Our min and max values are usually on the order of +/- 2 meters and our resolutions is usually around 1mm (though sometimes a bit better than that). So, when using pylas, we had set the scale in the header to 0.0001, so that we had one order of magnitude more resolution in the LAS file than our best possible accuracy.

This worked great in pylas, but with laspy2, it seems to be scaling the points when they are assigned in the wrong direction.

On pylas, if I executed the following code on a typical dataframe:
```
 las.header.x_scale = 0.0001
    las.header.y_scale = 0.0001
    las.header.z_scale = 0.0001
    
    las.x = colorizedPCL[:,0]
    las.y = colorizedPCL[:,1]
    las.z = colorizedPCL[:,2]
```

then lasinfo would give

```
scale factor x y z:         0.0001 0.0001 0.0001
  offset x y z:               0 0 0
  min x y z:                  -0.0412 -0.4811 0.0818
  max x y z:                  2.9329 1.2274 1.7042
```

With laspy2, the lasinfo output of the generated file is 

```
scale factor x y z:         0.0001 0.0001 0.0001
  offset x y z:               0 0 0
  min x y z:                  -0.0051 -0.0050 -0.0005
  max x y z:                  0.0209 0.0144 0.0212
```

It seems like there is a spurious scaling of the data by laspy with a scale factor of 100. Just to check my sanity and make sure I wasn't feeding it bad data, I did add some debug code just assigning to las.x, las.y, las.z to see the actual min/max of my data and it was 
```
xmin:-0.5099982241278208 xmax:2.0899958628936233 ymin:-0.499999825182655 ymax:1.4399942241674726 zmin:-0.05 zmax:255.0
```

It altogether may be the case, like in the last issue,  that  I am incorrectly using pylas and am not thinking about scaling correctly. My understanding was that the min/max of the actual data should always be whatever you set the data to be and that the scaling simply indicates how much the data is scaled by before writing to file because the LAS format uses integers to store the data.

**Comment by jpswensen** [comment]
I wanted to amend the report with a couple of quick test cases. In each case, I am including the relevant output of lasinfo. Note that the way I noticed this was that I often use displaz to view my LAZ files. I almost always scale down to 0.002 or 0.001 per sample so that it looks almost like a dense, filled pointcloud. In this case, I notices the points were huge compared to the axis bounds and realized that the point scaling was happening different than pylas.

**Example with no scaling**

```
las = laspy.create(point_format=8, file_version='1.4')
las.x = np.ones((10,))
las.x[0] = 0
las.write('test_noscale.las')
```

_lasinfo output:_
```
  scale factor x y z:         0.01 0.01 0.01
  offset x y z:               0 0 0
  min x y z:                  0.00 0.00 0.00
  max x y z:                  1.00 0.00 0.00
```

**Example with scaling down**
l```
as = laspy.create(point_format=8, file_version='1.4')
las.x = np.ones((10,))
las.x[0] = 0
las.header.x_scale = 0.0001
las.header.y_scale = 0.0001
las.header.z_scale = 0.0001
las.write('test_scalesmaller.las')
```

__lasinfo output__:
```
  scale factor x y z:         0.0001 0.0001 0.0001
  offset x y z:               0 0 0
  min x y z:                  0.0000 0.0000 0.0000
  max x y z:                  0.0100 0.0000 0.0000
```

**Example with scaling up**
```
las = laspy.create(point_format=8, file_version='1.4')
las.header.x_scale = 1
las.header.y_scale = 1
las.header.z_scale = 1
las.x = np.ones((10,))
las.x[0] = 0
las.write('test_scalebigger.las')
```

__lasinfo output__:
```
  scale factor x y z:         1 1 1
  offset x y z:               0 0 0
  min x y z:                  0 0 0
  max x y z:                  100 0 0
```

**Comment by jpswensen** [comment]
Sorry to keep commenting on my own issue, but think I may have sorted out my issue (and again it was probably me using pylas wrong and laspy having fixed it).

I was able to get things to work as expected by using the LasData.change_scaling function. I think the problem before was that I was only changing it in the LasHeader, so that it was updating the scale, but hadn't adjusted the internal long-data-type representation of the points accordingly.

The following examples works perfectly fine.

```
las = laspy.create(point_format=8, file_version='1.4')
las.x = np.ones((10,))
las.x[0] = 0
las.change_scaling([0.0001,0.0001,0.0001])
las.write('test_changescaling.las')
```

**Comment by tmontaigu** [comment]
I had a look at it, thanks for the small examples that allowed to reproduce.

So this is a second regression introduced by 8426cbc2991f88d64dbde336904199126a989a4d (so its a bug that does not appear in 2.0 but it does in 2.1).

What happens here is that since 2.1, the scales and offsets are also stored in the internal points array of the `LasData`,
and changing the scales and/or offsets by doing `las.header.scales = ` would not updated the offsets and scales stored in
the points array making them out of sync. 
So when setting the x,y or z coordinates after that would not produce the expected result.

So as you saw, in you last message, after the `LasData` object is created, it is safer to use `change_scaling` method which does the synchronisation properly.

I will push a fix as its a regression tho.
