### ISSUE TITLE
Scales and offsets not beeing taken into account when checking the max and min possible data values

### ISSUE THREAD

**Issue by PeterSanctus** [laspy/laspy#201]
Greetings,

Python=3.9.9
laspy=2.1.1

I'm trying to create a new las based on an array with X,Y,Z and its scales and offsets.

```python
las = laspy.create(point_format=1, file_version="1.2")
las.header.offsets = np.array([558000.0, 4500000.0, -0.0]) # these offsets comes from the original las file
las.header.scales = np.array([0.001, 0.001, 0.001])
las.x = self.data[sample]['X']
las.y = self.data[sample]['Y']
las.z = self.data[sample]['Z']
```

Because of the scales (mm) and offset values, my data has really big numbers like (X,Y,Z): 47909780, -32577290, -548860

When I try to assign the X values to las.x it raises an error: 

raise **OverflowError**(
   "Values given do not fit after applying offset and scale"
)

This happens in **laspy.point.dims.py** in the __setitem__ method. It seems to me when I debug it, it does not take into account the scales and offsets values specified. In this moment, inside __setitem__, the self.scale and self.offset are not the values that I specified before, they are the default ones; self.scale is 0.01 and self.offsse is 0.0; So when it goes to:

```python
max_allowed = self._apply_scale(info.max)
min_allowed = self._apply_scale(info.min)
```

The calculated values don't change, they stay on the defaults: 21474836.47, -21474836.47.
So because of this it raises the OverflowError at:

```python
if np.any(new_max > max_allowed) or np.any(new_min < min_allowed):
    raise OverflowError(
      "Values given do not fit after applying offset and scale"
     )
```

Is there something that I am missing?

thank you.

**Comment by tmontaigu** [comment]
Seems like the root of this problem is the same as in #199, its fixed on master

 You can try by installing master: ` pip install git+https://github.com/laspy/laspy`
