### ISSUE TITLE
Incorrect X,Y,Z values compared to other software

### ISSUE THREAD

**Issue by davodogster** [laspy/laspy#204]
I read the laz file into QGIS and Cloud compare and they match up perfectly. And Z values are on the scale 0 to Max height. But when I read into python it changes all the X,Y,Z values to some other scale. Would you know anything about why this is occurring??

I converted all files to las and tried but it's the same.

This is printing Z.min() and Z.max() for a point cloud laz file.
![image](https://user-images.githubusercontent.com/46079516/157169293-05a9fbe3-80fd-4b05-b775-7a6f7c49f8d1.png)

Z values should be in meters on the scale 0, 40m

Best regards, Sam

**Comment by tmontaigu** [comment]
I think that what you want is `z.max()` not `Z.max()`

**Comment by davodogster** [comment]
> I think that what you want is `z.max()` not `Z.max()`

@tmontaigu No, I think x,y,z don't exist. It's X,Y,Z

![image](https://user-images.githubusercontent.com/46079516/157348144-ed9fceb7-9d39-405b-85c6-b45050d5e4e2.png)

hmm I'm still trying to figure out why the values are wrong

**Comment by tmontaigu** [comment]
`lidar.x`
