### ISSUE TITLE
GeoKeyDirectoryVlr.from_crs fails with common coordinate reference systems

### ISSUE THREAD

**Issue by tayden** [laspy/laspy#211]
The `from_crs()` classmethod on the vlrs.known.GeoKeysDirectoryVlr makes it much easier to update the reference information for point clouds. Unfortunately, it fails when passed some `pyproj.CRS`s, including the very common `CRS("EPSG:4326")` (WGS84)

The issue seems to be this line: https://github.com/laspy/laspy/blob/master/laspy/vlrs/known.py#L528

It tries to set the GTCitationGeoKey using `crs.coordinate_operation.name`, which is not always defined.
An easy fix is to just use `crs.name` instead, which gives a more meaningful CRS name anyway.

If this sounds reasonable, I'll create a PR for it.

**Comment by tayden** [comment]
On second thought, it probably makes more sense to just not write the GTCitationGeoKey if the coordinate_operation is None on the crs.

**Comment by tmontaigu** [comment]
We should look at what the content of the VLR looks like when its generated by a tool'that has proper CRS support like PDAl and see what should be adjusted
