### ISSUE TITLE
laspy version 2.1.2 on pypi does not match laspy version 2.1.2 on github

### ISSUE THREAD

**Issue by shs613** [laspy/laspy#213]
While trying to determine how to change the spacial reference system of a las file in laspy, I ended up looking at the header.py source code. On line 409 in header.py from github, there appears the be a functino to edit the SRS  called add_CRS. 

This function does not exist in the version that I installed via pip. 

Additionally, running print(laspy.__version__) returns 2.1.2. So the pypi version number appears to match the github version number, but the code is different.

**Comment by tmontaigu** [comment]
That's because on github the default branch is master, and master is not 2.1.2 it contains the work in progress for the next release.

The 2.1.1 is [tagged](https://github.com/laspy/laspy/tree/2.1.2)
