### ISSUE TITLE
Point cloud's scan angle rank can not be read but pylas can

### ISSUE THREAD

**Issue by anieuwland** [laspy/laspy#223]
I have a point cloud of which laspy can not read the scan angle rank, but pylas can. I am using versions 2.1.2 and 0.4.3 respectively. I suspect the issue is caused by the file containing information that is not 100% according to spec.

However, laspy was able to open it regardless and this way we could 'correct' the scan angle rank by halving and reassigning. This allowed us to continue processing it. Unfortunately pylas doesn't seem to allow for this anymore.

```python
import pylas
import laspy

path = "pointcloud.las"
laspy.read(path).scan_angle_rank  # Fails with AttributeError: LasData object has no attribute 'scan_angle_rank'
pylas.read(path).scan_angle_rank  # Succeeds: array([-6699, -6823, -6932, ..., -8166, -6710, -8265], dtype=int16)
```

What causes this difference in behaviour? Are the developers open to supporting reading the scan angle rank in this case?

PS 1: I would like to share the point cloud, but it is very large and the whole thing is classified. I could share a segment of it if someone could help me with a command to slice it.

PS 2: I added two JSON snippets with PDAL metadata about the point cloud. Non-relevant information / entries have been left out.

```json
{
  "schema": {
    "dimensions":
    [
      {
        "name": "ScanAngleRank",
        "size": 4,
        "type": "floating"
      },
    ],
  },
  "stats": {
    "statistics":
    [
      {
        "average": 3.89175579,
        "count": 59582860,
        "maximum": 89.9940033,
        "minimum": -89.9940033,
        "name": "ScanAngleRank",
        "position": 9,
        "stddev": 32.4434898,
        "variance": 1052.58003
      },
    ],
  }
}
```

**Comment by tmontaigu** [comment]
since you have pdal you can try to make the file smaller by using the head filter http://pdal.io/stages/filters.head.html

**Comment by tmontaigu** [comment]
Ok so its juste that, its a file with point format 6 and so the field is available with the name `scan_angle`

**Comment by anieuwland** [comment]
Ahhh, that helps a lot. I didn't realize. Thank you.
