### ISSUE TITLE
Point Format 6 inconsistency between docs and code ?

### ISSUE THREAD

**Issue by spolloni** [laspy/laspy#226]
[These](https://laspy.readthedocs.io/en/latest/intro.html?highlight=format#point-format-6) docs indicate that point format 6 should have a `scan_angle_rank` dimension, but the code returns  [`scan_angle`](https://github.com/laspy/laspy/blob/fbb29737a2f70b4ffa0870c21b4351608fd64653/laspy/point/dims.py#L155) in `standard_dimension_names`, which is also consistent with [this ASPRS doc](https://www.asprs.org/wp-content/uploads/2010/12/LAS_1_4_r13.pdf)** (pages 15 and16). 

Are the docs wrong?

**Comment by tmontaigu** [comment]
yeah the docs are not correct since point format >= 6 have a `scan_angle` not a `scan_angle_rank`
