### ISSUE TITLE
How to store points that do not come from another LAS file?

### ISSUE THREAD

**Issue by larsmans** [laspy/laspy#23]
I was just trying to write out a bunch of points that do not actually come from selection among those in a LAS file, like the [tutorial](http://pythonhosted.org//laspy/tutorial.html) currently assumes, and I couldn't figure out how to set them. I.e., I have a `laspy.file.File` called `out`, I've managed to set the header and the data format, but then the `.points` is `None` and I can't find a way to get the right `dtype`. Just setting `out.points = my_array` doesn't work because the shapes don't match up.

Shouldn't there be some method that returns the NumPy dtype that will be used to represent points in the selected data format?

The points are in a NumPy array of shape `(N, 6)` (XYZRGB), produced by [python-pcl](/strawlab/python-pcl).

**Comment by chaoer** [comment]
@larsmans 
Hi, I was stuck by the  same problem. 
Had you solved this ?

Sincerely.
