### ISSUE TITLE
Generating Software limited to 31 characters

### ISSUE THREAD

**Issue by n4z4m3** [laspy/laspy#236]
In the LAS file specification it states that the generating software can be 32 characters, but it appears that laspy is treating it as a null terminated string of 32 bytes so it expects the last character to be null.

The result is that if you have a generating software in the header that actually uses up all 32 characters, laspy fails.

**Comment by tmontaigu** [comment]
You are right, and the same thing goes for system_identifier which does not needs to be null terminated.

However what do you mean by "fail", does it raise an exception ?

**Comment by n4z4m3** [comment]
Yeah. Sorry. I should have been more specific. Actually it does not "error" or raise an exception. It just throws a warning and truncates the string to 31 characters. Which can be a problem if that 31st character has valid information.

**Comment by n4z4m3** [comment]
And when I say "throws" a warning, I mean logs a warning (wih some stack trace).
