### ISSUE TITLE
Augment 'About' section

### ISSUE THREAD

**Issue by bramton** [laspy/laspy#241]
It would be nice if the link to the documentation of laspy is immediatly visible in the about section on the right hand side. 
Furthermore, to increase the visibility of the library also consider adding some relevant tags to the about section.

As an example, I would like to point out the about section from the Pytorch project:
https://github.com/pytorch/pytorch

**Comment by tmontaigu** [comment]
I added the links to the docs and some tags

**Comment by bramton** [comment]
👍 Looks, great! Thanks for the fast response.
