### ISSUE TITLE
append_points generates invalid LAZ

### ISSUE THREAD

**Issue by rdesparbes** [laspy/laspy#248]
# Description

The `append_points` method of the `LasAppender` generates an incomplete LAZ cloud in certain conditions. 

# Environment

- Windows 10
- python 3.8
- laspy 2.3.0
- lazrs 0.4.4

# Steps to reproduce

- Download the full `autzen.laz` point cloud (https://github.com/PDAL/data/blob/master/workshop/autzen.laz?raw=true)
- In the following script, set the `INPUT_CLOUDS_DIR_PATH` variable to the folder were the `autzen.laz` cloud has been downloaded:

```python
from pathlib import Path
from typing import List, Tuple

import laspy
import pytest
from _pytest.fixtures import SubRequest
from laspy import LasHeader, ScaleAwarePointRecord, LasData


INPUT_CLOUDS_DIR_PATH = "."


@pytest.fixture(params=[
    "output_cloud.laz",
    "output_cloud.las"
])
def output_cloud_path(request: SubRequest, tmp_path: Path) -> str:
    yield str(Path(tmp_path, request.param))


def get_input_point_clouds() -> List[Path]:
    return list(Path(INPUT_CLOUDS_DIR_PATH).glob("*.la[sz]"))


@pytest.fixture(params=get_input_point_clouds())
def input_cloud_path(request: SubRequest) -> str:
    return str(request.param)


def iter_points(points_list: List[ScaleAwarePointRecord]) -> Tuple[ScaleAwarePointRecord, slice]:
    offset: int = 0
    for points in points_list:
        yield points, slice(offset, offset + len(points))
        offset += len(points)


def check_write_append_read(
        output_cloud_path: str,
        points_list: List[ScaleAwarePointRecord],
        header: LasHeader
) -> None:
    with laspy.open(output_cloud_path, "w", header=header) as las_writer:
        las_writer.write_points(points_list[0])
    for points in points_list[1:]:
        if len(points):
            with laspy.open(output_cloud_path, "a") as las_appender:
                las_appender.append_points(points)
    final_cloud: LasData = laspy.read(output_cloud_path)

    for points, selector in iter_points(points_list):
        assert final_cloud.points[selector] == points


@pytest.mark.parametrize(
    "points_read_counts",
    [
        [-1],
        [1, -1],
        [49_999, -1],
        [50_000, -1],
    ]
)
def test_write_then_append_produces_valid_cloud(
        input_cloud_path: str,
        output_cloud_path: str,
        points_read_counts: List[int]
) -> None:
    with laspy.open(input_cloud_path) as las_reader:
        points_list: List[ScaleAwarePointRecord] = [
            las_reader.read_points(points_read_count)
            for points_read_count in points_read_counts
        ]

    check_write_append_read(output_cloud_path, points_list, las_reader.header)

```
- Launch the test with `pytest`

# Expected result

All the tests pass.

# Actual result

The test `test_write_then_append_produces_valid_cloud` fails when we try to read the generated point cloud for the following parameters: 
- `input_cloud_path`: `"autzen.laz"`
- `output_cloud_path`: `"output_cloud.laz"`
- `points_read_counts`: `[50_000, -1]` (we read 50 000 points, write them, reopen the written cloud in append mode, and write the remaining points)

It outputs the following error:

```
self = <laspy.lasreader.LazrsPointReader object at 0x00000252F97D6310>
n = 10653336

    def read_n_points(self, n: int) -> bytearray:
        point_bytes = bytearray(n * self.vlr.item_size())
>       self.decompressor.decompress_many(point_bytes)
E       pylaz.LazrsError: IoError: failed to fill whole buffer
```

# Suspects

This bug is observed when trying to write/append LAZ point clouds that are longer than 50 000 points, which is usually the default chunk size. I highly suspect the problem comes from *lazrs*, but unfortunately, I did not manage to implement a test case that illustrates that.

**Comment by tmontaigu** [comment]
The bug seems to be in 2 parts, one small in laspy and the other part in lazrs I identified them,
the difficulty will be choosing the most sensible fix in the lazrs part 🤔
