### ISSUE TITLE
append_points changes x/y coordinates of input files - bug?

### ISSUE THREAD

**Issue by daplew** [laspy/laspy#254]
I am trying to merge multiple las files into a single larger file using append_points() by defining the following function:
```
def append_to_las(in_las, out_las):
    with laspy.open(out_las, mode="a") as outlas:
        with laspy.open(in_las) as inlas:
            for points in inlas.chunk_iterator(2_000_000):
                outlas.append_points(points)
```
As a MWE, I have two las files that are each ~100MB and define one as `in_las` and one as `out_las`. Each file consists of XYZ points that should "follow on" from each other (they are neighbouring files from a continuous survey line) - see image below that demonstrates how they should follow on from each other 
![image](https://user-images.githubusercontent.com/54484466/216320024-ded04122-d5a4-40d3-bf95-d9e7f3c8276c.png)
However, when I merge the two files using `append_to_las()` the files end up stacked on top of each other with clearly false XY coordinates for the `in_las` file but correct coordinates for the `out_las` file. The Z value does not change. 
![image](https://user-images.githubusercontent.com/54484466/216323338-fa483ef7-3962-4d7f-acc7-3c14f188945c.png)
Similarly, when I create a las file from scratch using 
```
lasExample = laspy.create(point_format=laspy.read(in_las).header.point_format, file_version=laspy.read(in_las).header.version)
```
And append two files to the above `lasExample`, then both have clearly wrong XY points that start around 0,0 rather than 426000, 592400(ish).

I am using `laspy==2.3.0` on windows 10x64. I have tried `laspy==2.2.0` installed via `conda install -c conda-forge laspy` aswell as `laspy==2.3.0` from `pip`. I cannot provide the actual files I am working with due to licensing restrictions (although will try and see if I can get permission if it would help). The files are LAS 1.3, with point format 0.

Is this a bug?

**Comment by tmontaigu** [comment]
I think you have to call [change_scaling](https://laspy.readthedocs.io/en/latest/api/laspy.point.record.html#laspy.point.record.ScaleAwarePointRecord.change_scaling) before appending the points as the offsets are likely not the same in the two files.

**Comment by daplew** [comment]
Thank you @tmontaigu - I see how it works now. Appreciated.
