### ISSUE TITLE
Prefer one of GeoTIFF or WKT format CRS if both exist

### ISSUE THREAD

**Issue by n4z4m3** [laspy/laspy#266]
I have run into a couple of LAS files where for some reason the VLRs contain both Geotiff DirectoryKey tags and WKT format CRS information. I don't know how these LAS files were generated that they contain both, but obviously there is some software that must do this.

It seems that Laspy chooses the GeoTIFF format (or maybe the first one found in the file?) and at least for the files I found it did not contain all the information that the WKT format did and I want the WKT format.

There are a couple of things that could be done here.
1. If the GlobalEncoding bits have the WKT flag set, then use the WKT format if both exist. Possibly even for any point format >= 6 just use the WKT if they both exist because the LAS specification states that these point formats should all use WKT.
2. Add an option when opening/reading the LAS file to prefer one over the other if both exist.

In theory option 1 should be good enough, but I actually have come across a file that is point format 6, the GlobalEncoding does not have the WKT flag set, yet it has both GeoTIFF and WKT formats in the VLRs so I guess it is still a possibility. Whoever is creating these files must have software that is not compliant with the file format spec.

Unfortunately the example files I have are quite large (about 500 MB each) so I do not think I should attach them here, but I could possibly share them through some file sharing like OneDrive or Google Drive if they are necessary.

**Comment by tmontaigu** [comment]
Yes having the files as would be very helpful to be able to fix the problem and more importantly have tests.

Since points are not important in this case, you could try to filter the example files down to a very few points and they should normally still trigger the problem. Otherwise I'll take the 500MB files

> Whoever is creating these files must have software that is not compliant with the file format spec.

I bet laspy is not compliant on this part 😅

**Comment by hobu** [comment]
>  I don't know how these LAS files were generated that they contain both, but obviously there is some software that must do this.

There are quite a few softwares out there do this. I think it stems from not wanting to bother with implementing full WKT support.

One of the things that is currently proposed for LAS 1.5 is to remove GeoTIFF keys entirely, along with the older narrow PDRFs. Please comment at https://github.com/ASPRSorg/LAS/issues/128 if you have any opinions on that approach.

**Comment by n4z4m3** [comment]
Here are two sample files.   [Sample1](https://drive.google.com/file/d/1n4bSWadM0uA-dtsmMjbZf6JdWgws4KOR/view?usp=share_link) [Sample2](https://drive.google.com/file/d/12iZ4J2QM8S1N4FjXi-3q4P0O2d3lIwZM/view?usp=share_link)

The first one has both formats, but the GlobalEncoding bits set for the WKT flag. 
The second one has both as well, but the GlobalEncoding bits are unset for the WKT flag.

Both are Las v1.4 and point format 6 so in theory they should both use the WKT, but Laspy's parse_crs uses the GeoTiff.

Another note for the first sample is that since when Laspy reads from GeoTiff it uses the EPSG code rather than parsing all Geokeys, it also misses the fact that the units should be feet. Instead it reads them as meters, but if the WKT was used, it would properly have units of feet. This is why it is a big deal for this file, but maybe not as big of a deal for some others if the WKT and the Geotiff EPSG code line up.
