### ISSUE TITLE
Reading laz files

### ISSUE THREAD

**Issue by silyko** [laspy/laspy#27]
Thanks for developing this great library. Would be very cool if laspy also could read laz files. Just checked with a quick hack, which seemed to work (partly). The idea is to be able to call with a buffer object instead of a filename, something like:

prc=subprocess.Popen(["laszip","-olas","-stdout","-i","somefile.laz"],stdout=subprocess.PIPE,bufsize=-1)
data,stderr=prc.communicate()

f=FakeMmap(data)

with FakeMmap being something like (just a really, quick and dirty hack):

class FakeMmap(object):
    def **init**(self,data):
        self.data=buffer(data)
        self.pos=0
    def **getitem**(self,i):
        return self.data[i]
    def tobuffer(self):
        return self.data
    def flush(self):
        pass
    def fileno(self):
        return 0
    def close(self):
        pass
    def size(self):
        return len(self.data)
    def seek(self,bytes,pos):
        if pos>0:
            self.pos+=bytes
        else:
            self.pos=bytes
    def read(self,bytes):
        return self.data[self.pos:self.pos+bytes]
    def tell(self):
        return self.pos

Changed a few lines here and there in base.py and got it to work (mostly). Not sure if this is the right approach to take, but would enable laz-reading. Perhaps a keyword (is_buffer=True) in file.File ?

Cheers,
Simon

**Comment by hobu** [comment]
Turn this into a pull request and we can include it in the next release.

**Comment by grantbrown** [comment]
Definitely, this is a really cool idea.

**Comment by silyko** [comment]
Ok - I'll try to figure out how to best incorporate something like that and come up with a pull request. You can then decide if it makes sense.

**Comment by kbevers** [comment]
laz support was added in https://github.com/laspy/laspy/pull/28
