### ISSUE TITLE
Appending points to a LasData object

### ISSUE THREAD

**Issue by bszollosinagy** [laspy/laspy#270]
Assigning Numpy arrays to X Y or Z works fine. But if I add points in more than one session, by using `numpy.hstack()` I hit a strange bug. The arrays grow larger than the amount of points I actually added. See the reproducing code below.

### Workaround
Just assign the result of hstack to a temporary variable, and use that to fill  `las.x` and the other coordinates.

I don't know if this is caused some optimization that Numpy performs or some other reason, but I though I'd post the workaround. See the `no_bug()` function below for an implementation of the workaround. 

Another solution is to add your points to Numpy arrays and only assign them to the LasData objects once all the points are ready.

### Minimal reproducing code:

```import laspy
import numpy as np

def no_bug():
    new_hdr = laspy.LasHeader(version="1.4", point_format=7)
    new_hdr.scales = np.array([1.0, 1.0, 1.0])
    new_las = laspy.LasData(new_hdr)

    x = np.ones(42)
    y = np.ones(42)
    z = np.ones(42)

    # RESULTS OF HSTACK ARE STORED IN TEMP VARIABLES
    xx = np.hstack((new_las.x, x))
    yy = np.hstack((new_las.y, y))
    zz = np.hstack((new_las.z, z))

    new_las.x = xx
    new_las.y = yy
    new_las.z = zz

    print(f'{new_las.x.shape=}')
    print(f'{new_las.y.shape=}')
    print(f'{new_las.z.shape=}')


def with_bug():
    new_hdr = laspy.LasHeader(version="1.4", point_format=7)
    new_hdr.scales = np.array([1.0, 1.0, 1.0])
    new_las = laspy.LasData(new_hdr)

    x = np.ones(42)
    y = np.ones(42)
    z = np.ones(42)

    # RESULTS OF HSTACK ARE ASSIGNED DIRECTLY TO LAS ATTRIBUTES
    new_las.x = np.hstack((new_las.x, x))
    new_las.y = np.hstack((new_las.y, y))
    new_las.z = np.hstack((new_las.z, z))
    
    print(f'{new_las.x.shape=}')
    print(f'{new_las.y.shape=}')
    print(f'{new_las.z.shape=}')


def do_repro_bug():
    no_bug()
    with_bug()


if __name__ == "__main__":
    do_repro_bug()
```

### OUTPUT IS

 

new_las.x.shape=(42,)

new_las.y.shape=(42,)

new_las.z.shape=(42,)

new_las.x.shape=(126,)

new_las.y.shape=(126,)

new_las.z.shape=(126,)

 

 

### SHOULD BE

 

 

new_las.x.shape=(42,)

new_las.y.shape=(42,)

new_las.z.shape=(42,)

new_las.x.shape=(42,)

new_las.y.shape=(42,)

new_las.z.shape=(42,)

**Comment by grantbrown** [comment]
I think this is not a bug, just expected behavior. The first time you call

    new_las.x = np.hstack((new_las.x, x))

object now has 42 rows, which already includes a y and z dimension - they're coupled, and you can never have more x points than y points. Then, when you call 

    new_las.y = np.hstack((new_las.y, y))

new_las.y starts with 42 elements, and ends up with 84. Rinse and repeat, and you have the result you observe.
