### ISSUE TITLE
append_points() function has size limit at approximately 15.1GB?

### ISSUE THREAD

**Issue by CROdominik** [laspy/laspy#285]
Hi everyone,
I noticed consistend and strange behaviour using chunked approach and append points. I'm trying to create a very large laz file from many source las files, after which I want to make some tiled rasters.

I have noticed several times with different source files that at approximately 15.1GB appending points stop to work.

The error message itself is laspy exception "Could not initialize a laz backend: ". Nothing is wrong with the files as I tried conversions of files when the message appears, and it works. It always seems to be connected with the memory size. I also tried to delete cache regularly.

I tried to look into RAM and I assigned lots of ssd capacity to RAM (although this was not an issue based on monitoring activity). 

I also tried to chat with chatGPT but nothing obvious came out of that.

So is there a limit to appending points and is it really using chunking approach? is there some buffering that can create problems?

I use laspy 2.5.1, and miniconda on windows computer.

**Comment by tmontaigu** [comment]
What is the version of the file ? 1.2, 1.4 ?

I suspect you are exceeding the number of points allowed in a 1.2 file.

I tried to create a file and append fake points (all fields are 0s) everything was fine until the total numbe of points in the file exeeced the maximum allowed value, (an exception was raised but too late). 

If I then try to append points again to this file that already exceeds the maximum number of points allowed I also get a "Could not initialize a laz backend"

I'll add checks to append_points / write_points to raise an exception earlier.

**Comment by CROdominik** [comment]
OK, that could be it. It's actually file version 1.1.

I will then try converting the files to 1.4 when creating a large laz file. Thanks for the help!

**Comment by CROdominik** [comment]
Hi again; I can now confirm that version 1.4 exceeds this limit, so seems that the problem is solved. Thanks a lot!
