### ISSUE TITLE
laszip installation in ubuntu

### ISSUE THREAD

**Issue by asadclout** [laspy/laspy#294]
i am trying to install laszip using these following commands 
 - git clone https://github.com/LASzip/LASzip.git
  - cd LASzip
  - git checkout 3.1.0
  - cmake .
  - make
  - sudo make install
  - cd ..
  - wget https://lastools.github.io/download/LAStools.zip
  - unzip LAStools.zip
  - cd LAStools
  - make
  - sudo cp bin/laszip /usr/local/bin
  - sudo ln -s /usr/local/bin/laszip /usr/local/bin/laszip-cli
  
  but when i run "make" command after unzip it show this error
  
 cd LASlib && make
make[1]: Entering directory '/home/oc/LAStools/LASlib'
cd src && make
make[2]: Entering directory '/home/oc/LAStools/LASlib/src'
/bin/sh: 1: cd: can't cd to /home/jochen/srd
make[2]: *** [Makefile:155: all] Error 2
make[2]: Leaving directory '/home/oc/LAStools/LASlib/src'
make[1]: *** [Makefile:2: all] Error 2
make[1]: Leaving directory '/home/oc/LAStools/LASlib'
make: *** [Makefile:2: all] Error 2

**Comment by tmontaigu** [comment]
This is the laspy repostitory, not LASZip, so I can't help on this
