### ISSUE TITLE
Append data points to existing LAS file with header that contains extra dimensions.

### ISSUE THREAD

**Issue by PaschalisLagias** [laspy/laspy#295]
What is the best way of appending data points to an existing LAS file?
Is there a way to open it in "a" mode or do I have to read the file, pull the data, manipulate and re-write?

I am currently using laspy==2.1.2 and I have found the laspy.lasappender module with the LasAppender class:
[https://laspy.readthedocs.io/en/latest/api/laspy.lasappender.html](url)

Is it possible to provide an example of how this works or an alternative option for appending data?

Many thanks in advance.

**Comment by tmontaigu** [comment]
There is an example in the readme

```python
import laspy

with laspy.open('big.laz') as input_las:
    with laspy.open('ground.laz', mode="a") as ground_las:
        for points in input_las.chunk_iterator(2_000_000):
            ground_las.append_points(points[points.classification == 2])
```

**Comment by tmontaigu** [comment]
You have to convert your numpy array or pand thing into a [ScaleAwarePointRecord](https://laspy.readthedocs.io/en/latest/api/laspy.point.record.html#laspy.point.record.ScaleAwarePointRecord) or [PackedPointRecord](https://laspy.readthedocs.io/en/latest/api/laspy.point.record.html#laspy.point.record.PackedPointRecord)

```
points = lapy.ScaleAwarePointRecord.zeros(num_points, header=input_las.header)
points.intensity = ...
....

input_las.append_points(points)
```

**Comment by PaschalisLagias** [comment]
Thank you @tmontaigu for your help. I was able to do what I wanted. Merry Christmas and Happy New Year.

**Comment by tmontaigu** [comment]
Thanks, Merry Christmas and Happy New Year you too 🤗
