### ISSUE TITLE
List of 0 issue

### ISSUE THREAD

**Issue by ekrrems** [laspy/laspy#296]
We are currently in a project where we try to get features of points in .las file point cloud. Our data consists of general headers but when it comes to channel_id and enc_0 features, it returns every value as 0.0. I can see that we have that point feature on cloud compare like other features. Could you explain why it might be happening.

**Comment by tmontaigu** [comment]
Can you share a file ?

**Comment by tmontaigu** [comment]
🤔 🧐 🤨

**Comment by ekrrems** [comment]
Yeah, i have been working on that issue for days now. But just figured out the problem was caused by incorrect subsampling. Thank you for your time🙏
