### ISSUE TITLE
AttributeError: module 'laspy' has no attribute 'read'

### ISSUE THREAD

**Issue by prabanjanKAN** [laspy/laspy#306]
Python version =3.8
laspy version = 2.5.3

While trying to read a simple las file I am facing the following error "AttributeError: module 'laspy' has no attribute 'read." How can i resolve this?

The code:

import laspy

file = Bump1.las
las = laspy.read(file)

new_file = laspy.create(point_format=las.header.point_format, file_version=las.header.version)
new_file.points = las.points[las.classification == 1]

new_file.write('extracted_points.las')

**Comment by prabanjanKAN** [comment]
Code:

import laspy

las = laspy.read('Bump1.las')
las.points = las.points[las.classification == 2]
las.write('ground.laz')



Output: 
Traceback (most recent call last):
  File ".\laspydebug.py", line 3, in <module>
    las = laspy.read('Bump1.las')
AttributeError: module 'laspy' has no attribute 'read'

**Comment by tmontaigu** [comment]
Your environment is very likely broken, you should try recreating from scratch

**Comment by theoh-io** [comment]
I got the same error here tried with python 3.8 and 3.10 and recreating environment from scratch, didn't resolve..

**Comment by tmontaigu** [comment]
Ok, its funny to put reactions on every message, but do yo mind giving some actual information ? like OS, pip version, actual commands you run to setup the env and install laspy

Because the CI runs tests for all current python versions on Linux/maOS/Windows ans non fail

**Comment by rdesparbes** [comment]
> Code:
> 
> import laspy
> 
> las = laspy.read('Bump1.las') las.points = las.points[las.classification == 2] las.write('ground.laz')
> 
> Output: Traceback (most recent call last): File ".\laspydebug.py", line 3, in las = laspy.read('Bump1.las') AttributeError: module 'laspy' has no attribute 'read'

This looks a lot like you installed `laspy < 2.0.0`:

```console
$ conda create -n test python=3.8
$ conda activate test
$ pip install "laspy<2"
$ python -c "import laspy; laspy.read"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'laspy' has no attribute 'read'
```

**Comment by tmontaigu** [comment]
Indeed its very likely the source of the issue

**Comment by hobu** [comment]
I'll bump the pin to `numpy 1.23`
