### ISSUE TITLE
Provide pre-built wheels

### ISSUE THREAD

**Issue by adamjstewart** [laspy/laspy#308]
I'm curious how difficult it would be to provide pre-built wheels for laspy. Does laspy have any non-Python dependencies, or is it pure Python? If it's the latter, it might be as simple as uploading a single wheel. `python -m build` does this automatically: https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by tmontaigu** [comment]
But what is the advantage of wheels for something that is pure Python ?

**Comment by adamjstewart** [comment]
Primarily speed: https://realpython.com/python-wheels/#advantages-of-python-wheels

**Comment by tmontaigu** [comment]
I uploaded a wheel for 2.5.3

**Comment by adamjstewart** [comment]
Thank you!
