### ISSUE TITLE
Multiple point clouds structure in one LAS file

### ISSUE THREAD

**Issue by RauchLukas** [laspy/laspy#310]
Hey, 

I am looking for a way to export multiple point clouds (like a LiDAR sequence) and import it to CloudCompare. 
I don't want to create a unique file for every scan in the sequence, but also don't want to merge all scans to one huge point cloud. 

Is there a way in `laspy` to subgroup multiple np.arrays (like in a dict or a list) and if you are experienced with CloudCompare to properly disassemble them in CC? 

Thanks for your suggestions. 
cheers Lukas

**Comment by tmontaigu** [comment]
No its not possibe to do something like that in a way that easily integrates with other softwares

**Comment by RauchLukas** [comment]
@tmontaigu Thank you for the quick answer. In that case, I will stick to the single files...

**Comment by RauchLukas** [comment]
@tmontaigu  Thank you for the quick answer. In that case, I will stick to the single files...
