### ISSUE TITLE
LAS / LAZ Shuffle in custom attributes in QGIS

### ISSUE THREAD

**Issue by vincentBenet** [laspy/laspy#311]
[Linked to QGIS issue: https://github.com/qgis/QGIS/issues/56942]

### What is the bug or the crash?

Custom attributs are shuffle when LAZ file is open by QGIS. File are created using laspy package.

The shuffle seems to depends on the number of attributes, OS and QGIS version.
![image](https://github.com/qgis/QGIS/assets/38955854/80b0e832-82c3-4944-9f2d-c3136a7ae438)
![image](https://github.com/qgis/QGIS/assets/38955854/c04b6911-eeb8-4113-b963-ac97ce97b77a)

### Steps to reproduce the issue

1. Create a LAS file using laspy having multiple custom attributes.

```
def reproduct_issue(path: Path) -> None:
    header = laspy.LasHeader(point_format=3, version="1.4")
    las = laspy.LasData(header)
    las.add_extra_dims(
        [
            laspy.ExtraBytesParams(name="b", type=np.float64),
            laspy.ExtraBytesParams(name="bx", type=np.float64),
            laspy.ExtraBytesParams(name="by", type=np.float64),
            laspy.ExtraBytesParams(name="bz", type=np.float64),
        ],
    )
    las.x = np.linspace(0, 100, 100)
    las.y = np.linspace(0, 100, 100)
    las.z = np.linspace(0, 100, 100)
    las.b = np.full(100, 0, dtype=np.float64)
    las.bx = np.full(100, 1, dtype=np.float64)
    las.by = np.full(100, 2, dtype=np.float64)
    las.bz = np.full(100, 3, dtype=np.float64)
    las.write(str(path), laz_backend=laspy.LazBackend.LazrsParallel)
```

3. Open the file using QGIS with drag'n drop

4. Open a point attributs and see error with shuffle values

### Versions

QGIS 3.34.5 LTS
laspy 2.5.3

### Additional context

LAS & LAZ files : [files.zip](https://github.com/qgis/QGIS/files/15190410/files.zip)

**Comment by hobu** [comment]
I don't understand what you mean by 'shuffle'.

**Comment by vincentBenet** [comment]
I am using laspy to display magnetic survey by drone. On each point I have custom attributes "b", "bx", "by", "bz"

But once processed trought laspy, on QGIS, all "bz" values will be in "by" insteed.

Please note that I haven't successfully create a script that reproduce the issue...

Here is the script used that is shuffle vales:

`def write_mag(path: Path, data: npt.NDArray[np.float_], epsg_proj: int) -> None:
    header = laspy.LasHeader(point_format=3, version="1.4")
    header.add_crs(pyproj.CRS(f"EPSG:{epsg_proj}"))
    las = laspy.LasData(header)
    las.add_extra_dims(
        [
            laspy.ExtraBytesParams(name="bx", type=data["bx"].dtype),
            laspy.ExtraBytesParams(name="by", type=data["by"].dtype),
            laspy.ExtraBytesParams(name="bz", type=data["bz"].dtype),
            laspy.ExtraBytesParams(name="b", type=data["b"].dtype),
        ],
    )
    las.x = data["x"]
    las.y = data["y"]
    las.z = data["z"]
    las.bx = data["bx"]
    las.by = data["by"]
    las.bz = data["bz"]
    las.b = data["b"]
    las.write(str(path), laz_backend=laspy.LazBackend.LazrsParallel)
    logger.info("Wrote LAS file to %s", path)
`

**Comment by FlorianStasse** [comment]
Here is a function to easily reproduce the issue:

```python
def reproduct_issue(path: Path) -> None:
    header = laspy.LasHeader(point_format=3, version="1.4")
    las = laspy.LasData(header)
    las.add_extra_dims(
        [
            laspy.ExtraBytesParams(name="b", type=np.float64),
            laspy.ExtraBytesParams(name="bx", type=np.float64),
            laspy.ExtraBytesParams(name="by", type=np.float64),
            laspy.ExtraBytesParams(name="bz", type=np.float64),
        ],
    )
    las.x = np.linspace(0, 100, 100)
    las.y = np.linspace(0, 100, 100)
    las.z = np.linspace(0, 100, 100)
    las.b = np.full(100, 0, dtype=np.float64)
    las.bx = np.full(100, 1, dtype=np.float64)
    las.by = np.full(100, 2, dtype=np.float64)
    las.bz = np.full(100, 3, dtype=np.float64)
    las.write(str(path), laz_backend=laspy.LazBackend.LazrsParallel)
```

I'm using laspy 2.5.3 and Qgis LTS 3.34.5 to open the exported file.

If you open the exported file, you will see that the additional fileds do not have the expected value.

**Comment by hobu** [comment]
So is this a QGIS ticket or a laspy ticket?

**Comment by vincentBenet** [comment]
This is both as I don t know where the problem come from...

**Comment by vincentBenet** [comment]
Yes, after more investigation it seems laspy is doing a great job. But QGIS doesn't.
This software will create a **_.copc.laz_** file where the attributes will shuffles...
