### ISSUE TITLE
Empty string input parse_crs() should result in a None return, but instead a CRSError is thrown in pyproj

### ISSUE THREAD

**Issue by me9hanics** [laspy/laspy#314]
When reading a LAZ file that had no global coordinate reference system (e.g. measurements from radars have no global CRS by default), we ran into an issue: `pyproj: CRSError: Invalid WKT string: " (the string was empty).

The issue lays in the `laspy\header.py` file:

```
        if self.evlrs is not None:
            geo_vlr.extend(self.evlrs.get_by_id("LASF_Projection"))

        parsed_crs = {}
        for rec in geo_vlr:
            if isinstance(rec, (WktCoordinateSystemVlr, GeoKeyDirectoryVlr)):
                crs = rec.parse_crs()
                if crs is not None:
                    parsed_crs[type(rec)] = crs

        # Could not parse anything / there was nothing to parse
        if not parsed_crs:
            return None
```

The expected functionality is that even if there is nothing to parse, `rec.parse_crs()` returns nothing. The issue is, that `parse_crs(self)` just imports `pyproj` and uses `pyproj.CRS.from_wkt(self.string)` to return the result, but if there is nothing to parse, `from_wkt(cls, in_wkt_string: str)` will throw a CRSError. This way, we never get to a None return, but stop at an exception.

In our case, as we debugged it, the `rec.string` was an empty string which didn't get parsed and we should have ended up with a None according to the above code, but the exception wasn't handled. (We changed the code and caught the exception to return a None.)

A possible fix would be to check such cases and returning None before running `.parse_crs()`.

We used `laspy == 2.4.1` (`header.py` differs a bit from 2.5.0, but the functionality is the same) and `pyproj == 3.5.0`. Seems to be an issue with the current versions too.

**Comment by tmontaigu** [comment]
Thanks for the report
