### ISSUE TITLE
Writing ScaleAwarePointRecord ignores scaling and offsets

### ISSUE THREAD

**Issue by JoryKlaverstijn** [laspy/laspy#324]
Hello,

I was creating a small script to merge las files:
```python
import laspy

las_paths = ["path/to/file1.las", "path/to/file2.las"]
save_path = R"where/to/save/file3.las"

with laspy.open(las_paths[0]) as las_reader:
    header = las_reader.header
    header.partial_reset()

writer = laspy.open(
    save_path, 
    mode="w", 
    header=header
)

for p in las_paths:
    with laspy.open(p, "r") as las_reader:
        points = las_reader.read_points(las_reader.header.point_count)
    writer.write_points(points)

writer.close()
```
And my results were very messed up. I found out that it was because the scaling and offset of my source files were individually different. Now it seems to me that when I write a ScaleAwarePointRecord (which is what is returned when reading points), and writing these "scale aware" points to a new file, that it would take the scaling and offsets into account, but apparently it just copies the raw X, Y, and Z fields, as if it were a PackedPointRecord. Would it be a good idea to change the write_points function to take into account whether the points are scale aware? 

I understand I can use `points.change_scaling(scales=header.scales, offsets=header.offsets)`, but in my opinion it would make sense that write points automatically uses the given scaling and offsets when these are incorporated in the ScaleAwarePointRecord.

**Comment by tmontaigu** [comment]
Hum 🧐 maybe we can do that yes
