### ISSUE TITLE
Unable to install latest laspy with numpy 2 from conda-forge

### ISSUE THREAD

**Issue by rhkarls** [laspy/laspy#325]
My understanding is that laspy is compatible with numpy >= 2 and installing laspy 2.5.4 with numpy 2.x works using pip.

When I try to install laspy 2.5.4 with numpy 2.x using conda-forge channel I get conflicts. Is it pinned to `numpy<2.0a0`

```
(laspy_test) mamba install laspy=2.5 numpy=2

Looking for: ['laspy=2.5', 'numpy=2']

conda-forge/win-64                                          Using cache
conda-forge/noarch                                          Using cache
Could not solve for environment specs
The following packages are incompatible
├─ laspy 2.5**  is installable with the potential options
│  ├─ laspy [2.5.0|2.5.1] would require
│  │  └─ numpy >=1.21.6,<2.0a0 , which can be installed;
│  ├─ laspy [2.5.0|2.5.1|2.5.3|2.5.4] would require
│  │  └─ numpy >=1.23.5,<2.0a0 , which can be installed;
│  ├─ laspy [2.5.1|2.5.3|2.5.4] would require
│  │  └─ numpy >=1.22.4,<2.0a0 , which can be installed;
│  ├─ laspy 2.5.1 would require
│  │  └─ numpy >=1.26.0,<2.0a0 , which can be installed;
│  ├─ laspy 2.5.3 would require
│  │  └─ numpy >=1.26.3,<2.0a0 , which can be installed;
│  └─ laspy [2.5.3|2.5.4] would require
│     └─ numpy >=1.26.4,<2.0a0 , which can be installed;
└─ numpy 2**  is not installable because there are no viable options
   ├─ numpy [2.0.0|2.0.1|2.0.2|2.1.0|2.1.1] conflicts with any installable versions previously reported;
   ├─ numpy [2.0.0rc1|2.0.0rc2|2.1.0rc1] would require
   │  └─ _numpy_rc, which does not exist (perhaps a missing channel);
   └─ numpy [2.1.0|2.1.1] would require
      └─ python >=3.13.0rc1,<3.14.0a0 , which requires
         └─ _python_rc, which does not exist (perhaps a missing channel).

```

Cheers!

**Comment by tmontaigu** [comment]
From the log it seems that the conda package forbids numpy 2.0

I don't know how to change that as I'm not the maintainer of the conda package

**Comment by hobu** [comment]
>  I'm not the maintainer of the conda package

I took a quick look into this and I think one of its dependencies might have a numpy 1.x pin. I didn't look close enough though.

**Comment by hobu** [comment]
hmm, I don't know why I closed this 😦 

Anyway, I think the story is  https://github.com/laz-rs/laz-rs-python/pull/30 needs to be merged so we can have a new release so https://github.com/conda-forge/lazrs-python-feedstock/pull/23/ can be rerun and merged. Once that's merged, Python 3.13 migration can be completed. Once THAT is in, we can push another migration for Numpy 2.

**Comment by tmontaigu** [comment]
I'll do the laz-rs release this week

**Comment by weiji14** [comment]
This has nothing to do with `laz-rs` (the original error message from OP doesn't show `laz-rs` at all). The reason that laspy cannot be installed with numpy=2 is because the numpy2 migration PR at https://github.com/conda-forge/laspy-feedstock/pull/27 was closed prematurely, and so the `laspy` conda-forge package has not been re-built with NumPy 2.0 compatibility.

@hobu, you'll need to reopen https://github.com/conda-forge/laspy-feedstock/pull/27, and rebase it on top of recent changes. Your PR attempt at #29 with a simple rerender won't work.

**Comment by hobu** [comment]
Everything on conda-forge is rebuilt and should work with Numpy 2 now. Please reopen a ticket on the feedstock if this is still an issue.
