### ISSUE TITLE
Provide LAZ support using laz-perf

### ISSUE THREAD

**Issue by hobu** [laspy/laspy#33]
laz-perf provides a header-only C++11 implementation of LAZ read/write support. We can write some cython that provides VLR access and read/write support for laspy using this library.

**Comment by grantbrown** [comment]
In the meantime, read support should be up and running for those with laszip on their system path: [28](https://github.com/grantbrown/laspy/pull/28). Read/write would definitely be good though, and not relying on an external tool seems like the way to go.

**Comment by hobu** [comment]
This is happening in #60 but it will not be ready for 1.5.0
