### ISSUE TITLE
Looping over file and extracting coordinates

### ISSUE THREAD

**Issue by kalbermattenm** [laspy/laspy#36]
Is this still up-to-date : https://github.com/grantbrown/laspy/blob/master/laspy/file.py#L42-L45 ?

(I do not think so, but I am not sure...)

**Comment by grantbrown** [comment]
Hmm, it should be, but there is a typo. It should read:

    for p in f:
        print 'X,Y,Z: ', p.X, p.Y, p.Z

Point instances store the raw X, Y, and Z values. If you want the scaled values, it's simpler (and faster) to grab them directly from the file:

    x_scaled = f.x
    y_scaled = f.y
    z_scaled = f.z
    x_unscaled = f.X
    y_unscaled = f.Y
    z_unscaled = f.Z

**Comment by kalbermattenm** [comment]
OK, thanks a lot ! I was not to make it work like that (maybe I am getting a bit tired...)

I differed a bit from that (as `p.X` was not working for me...) (see https://github.com/kalbermattenm/las_extractor/blob/laspy/las_extractor/util/point_cloud_profiler.py#L110-L112)

**Comment by grantbrown** [comment]
I stand corrected, iterating over points returns unparsed Point instances. You could call "make_nice" on each point before accessing their coordinates, but that's going to be pretty slow. Your current approach seems the better one. I'll try to get that section of documentation fixed soon.

**Comment by kalbermattenm** [comment]
No worries ! It works great like that and we are accessing quite little LAS files, so it is quite fast (but many of them...).

Thanks for all your help !

**Comment by grantbrown** [comment]
No problem. If you're accessing lots of files, you may want to watch out for memory leaks as described in [this thread](https://github.com/grantbrown/laspy/issues/32). This is an outstanding bug which I haven't yet been able to track down satisfactorily.

**Comment by kalbermattenm** [comment]
OK... I did not really test my modifications in a production environment, but I will do... (I do not want to kill our prod servers...). Thanks for the advice !

**Comment by hobu** [comment]
Please reopen if this is still an issue going forward
