### ISSUE TITLE
Header point_format keyword does nothing

### ISSUE THREAD

**Issue by olliemath** [laspy/laspy#52]
Looking at the `__init__` method for the `Header` class, it's not used at all. How does one create a header with a different point_format?

**Comment by grantbrown** [comment]
Looking at it, you're correct (and I believe that's a bug). You should be able to modify the format on the header after creating it, however, as in [this example](http://pythonhosted.org//laspy/tut_part_2.html). 

If you (or someone else) wants to put together and test a pull request fixing the issue, that would be helpful.

**Comment by olliemath** [comment]
Thanks for the example. I'll see if I can put something together at the weekend (have other commitments right now)
