### ISSUE TITLE
Time for laspy v. 1.4.2 ?

### ISSUE THREAD

**Issue by kbevers** [laspy/laspy#54]
It's been almost a year since the last release. There hasn't been a lot of changes since then, but the project has seen some activity.

Personally I am holding back on using Laspy in prodcution code since the latest release doesn't write files fast enough. That has been improved significantly since the last release. A new release with the latest changes would satisfy my needs for using laspy in production.

**Comment by grantbrown** [comment]
This is a fair point, and I'll try to get to it soon. 

It's becoming clear (to me at least) that it would be helpful to hand off some of the responsibility for maintaining the official laspy repository; I'm no longer working on this professionally, and am having trouble finding the time to give it the attention it deserves. Thoughts, @hobu?

**Comment by hobu** [comment]
I can take over maintenance/release.

**Comment by hobu** [comment]
Also, @kbevers is trustworthy 😄

**Comment by kbevers** [comment]
Sure, I can give a helping hand as well

**Comment by grantbrown** [comment]
I've migrated laspy to a new organization, and made you both members. Howard was already on the pypi list of owners, but I've added kbevers now as well. 

Right now github.com/grantbrown/laspy should redirect to github.com/laspy/laspy. One of the things we'll want to do is update the documentation to reflect the change. Once that's out of the way, I'll go ahead and get my own contributor fork, and try to chip in when I can. 

Thanks for helping out on this, it's probably a good thing to get actual LIDAR people more involved :laughing:

**Comment by hobu** [comment]
Ok @kbevers release away 😄

**Comment by kbevers** [comment]
@grantbrown Thanks. 

> Ok @kbevers release away 😄

Will do! I haven't looked too closely into this yet. Is this just a matter of bumping the version number in ```setup.py``` and ```laspy/__init__.py``` and the run ```publish.sh```?

**Comment by grantbrown** [comment]
Pretty much (though my memory is honestly a little hazy - I don't do this much as you've noticed). Publish.sh won't upload a windows installer, for that you'll need to do some combination of bdist and wininst: [more here](https://docs.python.org/2/distutils/builtdist.html).

**Comment by grantbrown** [comment]
Thanks so much by the way!

**Comment by kbevers** [comment]
So, there it is. laspy v. 1.4.2 is released. I haven't done the windows stuff yet, but I'll do that later when I'm using a windows computer. If it is even necessary, don't people install python packages with pip anyway?

**Comment by brycefrank** [comment]
Is there any talk for a Python 3 compatible version?

**Comment by grantbrown** [comment]
@brycefrank: check out [this pull request](https://github.com/laspy/laspy/pull/45). If you want to take a look at the remaining testing issues, we should be able to get it merged in and start supporting python 3.

**Comment by rgommers** [comment]
> If it is even necessary, don't people install python packages with pip anyway?

They do, although it's starting to be a minority in the scientific world. But you want to build wheels with ``python setup.py bdist_wheel``, not .exe or .msi (which were mentioned above).

**Comment by kbevers** [comment]
@rgommers [That's exactly what I did](https://github.com/laspy/laspy/blob/master/publish.sh#L3). That should satisfy everyones needs.

**Comment by rgommers** [comment]
Great, thanks!
