### ISSUE TITLE
Wrong 'extra_bytes' values

### ISSUE THREAD

**Issue by fri-end** [laspy/laspy#57]
Hi,
I'm using laspy 1.4.2/numpy 1.11.2 installed via conda on Ubuntu 14.04 that runs on VirtualBox, and I'm getting wrong values when accessing extra_bytes of my LAS file (see [link](https://www.dropbox.com/sh/dj04kt4c60x9d32/AABWKAt_-e8n5hvTG4sK0qj3a?dl=0)):

```
inFile = laspy.file.File('960.las', mode = "r")
print inFile.height_above_ground
```

I'm getting random, negative values instead of actual height values.
Thanks for any advice,
Yuri

**Comment by kbevers** [comment]
To me it seems like you get the correct values, it is just not what you are expecting. The extra bytes values you are seeing are unscaled. Extra bytes support in laspy is not very advanced so you'll have apply an offset and scaling factor yourself.
That info seems to be available in a  Extra Byte Variable Length Record that follows the LAS1.4 spec, even though the file is LAS1.2. Laspy reads the name of the dimension from it, but at the moment it doesn't apply the offset and scaling values.

**Comment by kbevers** [comment]
The file was created with ```lasheight```. The scaling factors are mentioned in the [README](http://www.cs.unc.edu/~isenburg/lastools/download/lasheight_README.txt). I'd start by reading that carefully. If you know with which paramters ```lasheight``` was called you should be able to figure out how the data should be scaled properly.

**Comment by fri-end** [comment]
@kbevers Thanks for this suggestion, I did manage to properly scale heights above ground using the offset of 25000 and scale of 0.01. However, I used a proprietary software to find these values. I was hoping to be able to access this information using LasPy's in-built information. Unfortunately, after running
```
print inFile.header.vlrs[1].scale
print inFile.header.vlrs[1].offset
```
I'm getting errors:
AttributeError: VLR instance has no attribute 'scale'
AttributeError: VLR instance has no attribute 'offset'

**Comment by kbevers** [comment]
I don't think laspy's VLR capabilities are that advanced yet. Ideally laspy would scale the values for you. If this is an important feature for you, I suggest you implement it yourself and submit the changes in a PR. I'm happy to merge any improvements.

**Comment by grantbrown** [comment]
@fri-end I haven't dug into this in any depth, but you should be able to get the reported offset (and other info) as follows:

    import laspy
    import numpy as np

    f = laspy.file.File("./960.las")
    print(f.header.vlrs[1].extra_dimensions[0].description)
    print(f.header.vlrs[1].extra_dimensions[0].name)
    print(f.header.vlrs[1].extra_dimensions[0].scale)
    print(f.header.vlrs[1].extra_dimensions[0].offset)

**Comment by fri-end** [comment]
@grantbrown Thanks for this suggestion. It works like a charm!
@kbevers  If I find time to add functionality to automatically scale 'extra_bytes' fields at some point, I will send a pull request. Thanks again!
