### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by hobu** [laspy/laspy#58]
It looks like there's a full fork that has Python 3 support 

https://github.com/sethrh/laspy

**Comment by kbevers** [comment]
Yeah, it's been here as a PR for a while: https://github.com/laspy/laspy/pull/45

Hasn't been merged yet since not all tests pass. Unfortunately the submitter seem to have lost interest again. If no one fixes the tests I'll do it myself eventually.

**Comment by hobu** [comment]
#62 has it covered.
