### ISSUE TITLE
laszip support

### ISSUE THREAD

**Issue by ryanfox** [laspy/laspy#59]
Hi there, are there plans to add compression support to laspy?  Per https://github.com/laspy/laspy/blob/master/laspy/header.py#L969 :

    Controls compression for this file.
    If True, the file is compressed with lasZIP compression and will
    be written with lasZIP compression.  If False, the file is not
    compressed. Not implemented in laspy.

I also tried `myfile.header.compressed = True` and `myfile.header.set_compressed(True)`, just to give it a shot; both seem to have no effect.  Is adding support for this on the table?

**Comment by hobu** [comment]
I have been slowly working on a LAZ Python extension in https://github.com/hobu/laz-perf/tree/master/python 

The basic compressor is working, but not LAZ. Some significant effort is still required, but the task is progressing a little. Sorry I can't provide more at the moment.

**Comment by grantbrown** [comment]
We support reading LAZ files (in a somewhat suboptimal way) if you have laszip on your path, but haven't implemented actual compression.

**Comment by ryanfox** [comment]
Got it.  Right now I'm just shelling out to laszip, so it's not a huge deal.  Do you have plans to integrate it in the future?

**Comment by grantbrown** [comment]
The preference would be to depend on Howard's completed tool to reduce the number of external dependencies needed. If it's something that you'd be interested in implementing, however, we could certainly implement a write mode for the Fake-mmap feature that adds laz reading capabilities in the meantime. 

Some relevant commits:

[1](https://github.com/laspy/laspy/commit/3d44d589653d77f7e05468795133b695d6fa408a)
[2](https://github.com/laspy/laspy/commit/610542bbca307b45488d1ec3682a0a8249a87c11)
[3](https://github.com/laspy/laspy/commit/72d5c96af1bd852ac7ba30d870421d3b5f825374)
[4](https://github.com/laspy/laspy/commit/43d221548de58566555b1dd9906bf8c63f68d8d3)
[5](https://github.com/laspy/laspy/commit/de6d92a1ddfaa3066b79ffe07d83027a6325d483)

**Comment by ryanfox** [comment]
Thanks for all your help.  I do have a workaround currently, so it's not the end of the world.  I'll keep an eye on it though 👍
