### ISSUE TITLE
Cannot open file in read-only mode without write permission

### ISSUE THREAD

**Issue by Ellon** [laspy/laspy#66]
When we try to open a read-only file (no write permission) with mode="r", it is changed internally to "r+" before trying to open the file on[ laspy.base.DataProvider.open()](https://github.com/laspy/laspy/blob/master/laspy/base.py#L122).

Mode "r+" expects write permission, so the open fails, and laspy stops with the exception raised on [laspy/base.py, line 128](https://github.com/laspy/laspy/blob/master/laspy/base.py#L128)

Problem found on laspy 1.5.0.

**Comment by kbevers** [comment]
You seem to already have figured out what the problem is. Do you mind submitting a PR with a fix?

**Comment by Ellon** [comment]
Not at all, here it is.

Didn't do it before because I saw many other places where laspy.base.DataProvider.open() was being called directly with "r+b" or "w+b", and I was afraid of side effects. But after further inspection I saw all these calls were done always from inside laspy.base.Writer, so I think these calls are OK.
