### ISSUE TITLE
Usage of API and documentation for projection metadata in las files

### ISSUE THREAD

**Issue by jeffreywolf** [laspy/laspy#68]
I have hesitated to ask this question, because I don't know if this is the correct forum to ask questions that are mainly usage related. However, I have decided that this question is both an API issue and documentation issue so is relevant to ask here.

A common problem for people working on lidar datasets is rasterizing point clouds.  Documenting how to pull out the projection information from each las file version would make it much easier to write code that can rasterize a point cloud. 

This is a feature request to document how to easily obtain the metadata needed for using lidar data read by laspy that is required to produce a georeferenced raster using GDAL.  The main challenge I have run into is getting the projection from the las file using laspy.  I've yet to figure out how to do this with 1.0 las files that I know have projection metadata. 

More generally, is there any interest in having a user forum to discuss usage of laspy where both laspy users and developers can ask questions not directly related to development of laspy, but geared at laspy usage?  Laspy is a library that sits in a wonderful ecosystem of open source geospatial software that is well supported by Python developers.  The laspy documentation does not explain how to use laspy in the broader context of other geospatial libraries -- such as GDAL -- that can be used to rasterize a point cloud.

**Comment by grantbrown** [comment]
My 2c on the question of forums is that the laspy community is small enough such that questions can be best addressed here, but I don't feel strongly about it. 

As far as projection information goes, it should be pretty straightforward to grab it from the VLRs.
    
    # Get the record_id for each available vlr in file.File f:
    [x.record_id for x in f.header.vlrs]

**Comment by grantbrown** [comment]
Sorry, hit the wrong button. 

I'm agnostic about the idea of a forum, though I think it's useful to get feedback like this here. In this case, I think you've highlighted both a good feature to consider adding, and a gap in the documentation. 


As far as projection information goes, you should be able to find it in the VLRs (though whether it's in a format that's immediately useful to you is another question). 

    userIDs = [x.user_id for x in f.header.vlrs]
    recIDs = [x.record_id for x in f.header.vlrs]
    # What's in a VLR?
    f.header.vlrs[0].body_summary()
    # Parsed data
    vlrData = f.header.vlrs[0].parsed_body

Maybe if you could give some examples of the format you'd need the data in, we can get an example script put together for you to test. Once we get it ironed out, I think this is an obvious use case to add to the documentation.

**Comment by bvanderj** [comment]
Lurker here. Hope this is an appropriate place for questions.

As far as i can tell, there is no way to write projection information (e.g. EPSG, proj4 string) into the las header using the current release of laspy.  Am i correct in that assessment?

**Comment by grantbrown** [comment]
Projection information is located in the VLRs (and/or EVLRs, depending on the file version), which are readable and writeable as a list of Laspy VLR (or EVLR) objects. 

For writing projection information, the trick is to construct an appropriate VLR - a task which is insufficiently documented (and which I only vaguely remember how to do). Would you be willing to put together a specific example of data you'd like to add to a file as part of a projection task? That might help us add something useful to the docs.

**Comment by bvanderj** [comment]
Absolutely, will get it put together tonight.

**Comment by jpapadak** [comment]
This issue seems to have died, but I'm also interested in this. In my example, I have points with spatial reference in UTM zone 11N. How can I add this information to the VLRs using laspy?

**Comment by tmontaigu** [comment]
With #197  and #215 I consider this closed
