### ISSUE TITLE
Read only the Header in LAS File

### ISSUE THREAD

**Issue by JeremyBYU** [laspy/laspy#69]
Hi, 
I was just wondering if there was a way to read *only* the header from the .laz/.las file.  I have to process a bunch of .laz files and just needed to know their bounding boxes.  

From what I am seeing the whole data is read in once `File(path)` is called (including points mapped to numpy array).  I tried to look at the code for `HeaderManager` and calling it directly but cant seem to get it to work.

Thanks!

**Comment by kbevers** [comment]
You can open the file in "r-" mode. See [this test function](https://github.com/silyko/laspy/blob/5278b31975075b4e95d5c316abf7b0daf0a8f7e5/laspytest/test_laspy.py#L816-L821) for an example

**Comment by JeremyBYU** [comment]
Awesome, I can't believe I didn't see this in the [source code](https://github.com/laspy/laspy/blob/master/laspy/base.py#L153). Thanks for the quick reply! Might be good to have this in the docs somewhere (unless I missed it!)

**Comment by kbevers** [comment]
> Might be good to have this in the docs somewhere (unless I missed it!)

You didn't. Feel free to submit a PR with updated docs!
