### ISSUE TITLE
How to install laspy in an anaconda environment?

### ISSUE THREAD

**Issue by mgooty** [laspy/laspy#72]
I have run the below command to install `laspy`:

`conda install laspy`

Got the following error:

```
Fetching package metadata ..........

PackageNotFoundError: Package missing in current osx-64 channels:
 - laspy
```

**Comment by mccarthyryanc** [comment]
If you don't already have your environment created:

```bash
conda create -n laspy-env
```

Activate you environment, and then install via pip:

```bash
source activate laspy-env
pip install laspy
```

Conda works with pip to put everything into the correct environment paths.

**Comment by grantbrown** [comment]
Appears resolved
