### ISSUE TITLE
LAZ file Project ID

### ISSUE THREAD

**Issue by assismauro** [laspy/laspy#76]
I'm getting a no treated exception when trying to access header.project of a LAZ (laszip compressed) file:

f=laspy.file.File(r"G:\TRANSECTS\VALIDATING\NP_T-0001.laz")
print f.header.project_id

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3066, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-8a80b4d3da38>", line 1, in <module>
    print f.header.project_id
  File "C:\Anaconda\lib\site-packages\laspy\header.py", line 707, in get_projectid
    return(uuid.UUID(bytes =p1+p2+p3+p4))
TypeError: unsupported operand type(s) for +: 'memoryview' and 'memoryview'

It works fine in a LAS file.

**Comment by Sajjadmanal** [comment]
Hi @assismauro Were you able to read .LAZ file via laspy?

**Comment by assismauro** [comment]
Yes, it works.


________________________________

**Comment by Sajjadmanal** [comment]
@assismauro How you read .laz files?

**Comment by hobu** [comment]
@Sajjadmanal please stop spamming the repository with this question.

**Comment by Sajjadmanal** [comment]
@hobu Sorry if it meant spam for you. I was just curious to know the answer to this question.
