### ISSUE TITLE
Laszip support on Linux (Ubuntu, 16.04)

### ISSUE THREAD

**Issue by CheeseAnt** [laspy/laspy#79]
I may be wrong about this, but having a look at the source of base.py, I can see that only binaries are searched for, which are not present on the linux installations of laszip. So, is this module only compatible with opening .laz files on windows?

If anyone has a method of obtaining a binary version for linux systems, that would be equally appreciated, as tips to modifying the code for compatibility.

**Comment by kbevers** [comment]
> So, is this module only compatible with opening .laz files on windows?

No.

> 

> If anyone has a method of obtaining a binary version for linux systems, that would be equally appreciated, as tips to modifying the code for compatibility.

There's an example [here](https://github.com/Kortforsyningen/DHMQC/blob/master/.travis.yml#L20-L32). Relevant excerpt: 
```
 - git clone https://github.com/LASzip/LASzip.git
  - cd LASzip
  - git checkout 3.1.0
  - cmake .
  - make
  - sudo make install
  - cd ..
  - wget http://lastools.org/download/LAStools.zip
  - unzip LAStools.zip
  - cd LAStools
  - make
  - sudo cp bin/laszip /usr/local/bin
  - sudo ln -s /usr/local/bin/laszip /usr/local/bin/laszip-cli
```

**Comment by CheeseAnt** [comment]
Thank you, i feel silly for not having found this before.

**Comment by kbevers** [comment]
If only there was a website included in those links that you could open in a browser and find what you need...

**Comment by Nicholas-Mitchell** [comment]
Clicking on the two links I sent does now send me to a page where I can select a file to download... When I posted originally, the domain lastools.org was not responding at all.

**Comment by glw** [comment]
I had issues unzipping it on my Linux VM. I had to download via Windows and unzip, then copy the directory back to my VM.

**Comment by Bornlove** [comment]
> I had issues unzipping it on my Linux VM. I had to download via Windows and unzip, then copy the directory back to my VM.

I did that way and it zipped off, Appreciate

**Comment by davidcaron** [comment]
The link to LAStools should be:

`wget https://lastools.github.io/download/LAStools.zip`

I also had issues unzipping it, because the first link returned an html document 🙂

**Comment by asadclout** [comment]
when i run "make" command after unzip it show this error

cd LASlib && make
make[1]: Entering directory '/home/oc/LAStools/LASlib'
cd src && make
make[2]: Entering directory '/home/oc/LAStools/LASlib/src'
/bin/sh: 1: cd: can't cd to /home/jochen/srd
make[2]: *** [Makefile:155: all] Error 2
make[2]: Leaving directory '/home/oc/LAStools/LASlib/src'
make[1]: *** [Makefile:2: all] Error 2
make[1]: Leaving directory '/home/oc/LAStools/LASlib'
make: *** [Makefile:2: all] Error 2
