### ISSUE TITLE
Unable to read the converted .pcd file 

### ISSUE THREAD

**Issue by niranjanreddy891** [laspy/laspy#80]
I can convert .las file to .pcd without any difficulty. But when I am reading the .pcd file which is generatred from .las file using laspy, I am getting this error 
`OSError: error while loading pointcloud from 'E:/Lidar-practice/New-data/New folder/output.pcd' (format='pcd')`.   Thanks in advance

**Comment by grantbrown** [comment]
laspy does not read or generate pcd files, so it sounds like you're probably just using laspy as a fancy way to change the file extension from las to pcd, without changing the underlying format. Then, when you use python-pcl to read the file, it rightly complains that the file is not a pcd file.
