### ISSUE TITLE
How to solve this issue

### ISSUE THREAD

**Issue by niranjanreddy891** [laspy/laspy#82]
`laspy.util.LaspyException: Error opening file. Do you have the right permissions?
`
I am facing this error while compiling the program

**Comment by grantbrown** [comment]
Is it failing when you run:

    python setup.py install

, or are you using pip or some other installation method?

If this is when it fails, I'd recommend:

    python setup.py install --user

Let us know if that helps.

**Comment by niranjanreddy891** [comment]
I am using pip to install

**Comment by niranjanreddy891** [comment]
I am facing this issue while comping the program.

**Comment by grantbrown** [comment]
Can you provide more details?

* What command, precisely, are you running?
* What Python version are you using?
* What operating system are you using?
* What is the full error and traceback provided?

**Comment by niranjanreddy891** [comment]
This happened when I was trying to execute python program not with the command. 
I am using python-2.7 with win-7 64 bit installed. This is what the error it throws when executing the program `laspy.util.LaspyException: Error opening file. Do you have the right permissions?`

**Comment by kbevers** [comment]
Dude, you are not making it easy for us to help you. Do you expect us to be mind readers? What command are you running to get this error?

**Comment by niranjanreddy891** [comment]
Thanks for your help @grantbrown and @kbevers. I figured out the issue.

**Comment by kbevers** [comment]
Please explain how you solved the problem so others can benefit from your experience later on.

**Comment by niranjanreddy891** [comment]
I included this  `import laspy.util.Exception` in my program

**Comment by ShadesEuro** [comment]
I tried import laspy.util.Exception this.
but it shows this
Traceback (most recent call last):
  File "las2pcd.py", line 4, in <module>
    import laspy.util.Exception
ImportError: No module named Exception
