### ISSUE TITLE
How to use lasviewer in laspy

### ISSUE THREAD

**Issue by niranjanreddy891** [laspy/laspy#83]
Can anyone please provide me a sample on how to use `lasviewer `for visualization with RGB colors. I went through the documentation. But I couldn't find an example on how to use `lasviewer`. Thanks in advance

**Comment by kbevers** [comment]
Try reading the docs again: http://laspy.readthedocs.io/en/latest/laspy_tools.html Read the section on lasviewer.

But really you are much better of using another viewer like cloudcompare.

**Comment by niranjanreddy891** [comment]
@kbevers, I already tried using the official documentation which you mentioned. But I need a sample. The samples available in the documentation are not helpful for me. Can you provide me any sample code?

**Comment by kbevers** [comment]
lasviewer is not code. It's a command line application. There is no sample code to provide you with. You run it from a command line with: 

```
lasviewer ./path/to/las/file
```

If that is not what you need, you'll have to seek a solution to your problem outside of laspy I'm afraid.

**Comment by niranjanreddy891** [comment]
@kbevers, I did run it through command prompt only, but didn't worked. But I am looking for a code so that I can include that code in my program.

**Comment by kbevers** [comment]
You'll have to dig through the laspy code to figure out a way to do that. I'm closing this as there's no immediate solution to your problem.
