### ISSUE TITLE
laszip was installed in source.

### ISSUE THREAD

**Issue by bw4sz** [laspy/laspy#84]
[Crossposted](https://stackoverflow.com/questions/49500149/laspy-cannot-find-laszip-when-is-installed-from-source-laszip-is-in-path) if more appropriate: 

I am working on a HPC environment and do not have root access. I installed laszip from source.

# Install laszip from source

    module load git
    git clone https://github.com/LASzip/LASzip.git
    git checkout tags/2.0.2
    cd LASzip

Make files in the build directory.

    mkdir build
    cd build
    module load cmake
    module load gcc
    cmake .. -DCMAKE_INSTALL_PREFIX=/home/b.weinstein/LASzip/build 
    make
    make install

Add paths

    export LD_LIBRARY_PATH="/home/b.weinstein/LASzip/build/lib:$LD_LIBRARY_PATH"
    export PATH="/home/b.weinstein/LASzip/build/bin:$PATH"

Make sure it works locally

    (pangeo) [b.weinstein@c30a-s26 bin]$ pwd
    /home/b.weinstein/LASzip/build/bin
    (pangeo) [b.weinstein@c30a-s26 bin]$ laszip-config --version
    2.0.2

Go to a new directory to test linking

    cd ~
    (pangeo) [b.weinstein@c30a-s26 ~]$ laszip-config --version
    2.0.2

# Test from python

    (pangeo) [b.weinstein@c30a-s26 ~]$ python
    Python 3.6.4 | packaged by conda-forge | (default, Dec 23 2017, 16:31:06) 
    [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import laspy
    >>> test_file=laspy.file.File("/ufrc/ewhite/s.marconi/NeonData/2017_Campaign/D03/OSBS/L1/DiscreteLidar/ClassifiedPointCloud/NEON_D03_OSBS_DP1_412000_3283000_classified_point_cloud.laz")
    Traceback (most recent call last):
      File "/home/b.weinstein/miniconda3/envs/pangeo/lib/python3.6/site-packages/laspy/base.py", line 204, in map
        self._mmap=FakeMmap(self.filename)
      File "/home/b.weinstein/miniconda3/envs/pangeo/lib/python3.6/site-packages/laspy/base.py", line 57, in __init__
        data = read_compressed(filename)
      File "/home/b.weinstein/miniconda3/envs/pangeo/lib/python3.6/site-packages/laspy/base.py", line 37, in read_compressed
        raise(laspy.util.LaspyException("Laszip was not found on the system"))
    laspy.util.LaspyException: Laszip was not found on the system
    

How can I tell laspy where to look for laszip? Is this a PYTHONPATH v PATH issue?

**Comment by kbevers** [comment]
You need the `laszip-cli` application which is not installed with LASZip. See https://github.com/laspy/laspy/issues/79.
