### ISSUE TITLE
How to set class ID(ASPRS) to las points

### ISSUE THREAD

**Issue by pradAI** [laspy/laspy#87]
Hi, I have separated ground and non-ground points from las data. I would like to set the class ID for each point. I have to set ground points to class ID is 2 as per ASPRS standards. please help me how to set class ID

**Comment by grantbrown** [comment]
As in, set the point classification as defined in Table 9 of [the specification](https://www.asprs.org/wp-content/uploads/2010/12/LAS_1_4_r13.pdf)? You can access that via the `classification` property on file objects. Alternatively, if you've formatted the bytes properly, you can access this via the `raw_classification` property, which is faster.
