### ISSUE TITLE
create LAS file: fails to reset the number of points.

### ISSUE THREAD

**Issue by romulogoncalves** [laspy/laspy#88]
We are trying to create a LAS file with less points than the input file. Here is the code:
```
in_pc = File(tile_path, mode='r')
header = in_pc.header.copy()
header.point_records_count = (tile_size / grid_cell_size) * (tile_size / grid_cell_size)
in_pc.close()

out_LAS = File(tile_out_path, mode = "w", header=header)

print("The number of points is: %d " % out_LAS.header.point_records_count)
```

The print statement shows that we the open file has a header saying 4 points
```
The number of points is: 4
```

However, laspy complains that the number of records in the header is different than the number of records to be added when we set `X`:
```
out_LAS.x = x
```
Gives:
```
WARNING: laspy found invalid data in header.point_records_count.
                            Header.point_records_count = 0, and 4 records actually detected.
                            Attempting to correct mismatch.
```

We do not understand why the [manager](https://github.com/laspy/laspy/blob/master/laspy/base.py#L164) is not using the new `point_records_count`:
```
if self.manager.header.point_records_count
```

How is manager initiated? We thought it would use the header information. Should the reset be done in a different way?

**Comment by romulogoncalves** [comment]
We were writing to a mounted file system which was the reason for our issues. Saving the file into the local file system solved the issue.

**Comment by Crear12** [comment]
Try this, it worked in my environment:
inFile = laspy.file.File(LasFilePath, mode="r")
OutHeader = inFile.header.copy()
OutHeader.point_return_count[0]=100

outFile = laspy.file.File("Output.las", mode = "w",vlrs = inFile.header.vlrs,header = OutHeader)
outFile.points = inFile.points[:100].copy()
outFile.X[:] = inFile.X[:100]
