### ISSUE TITLE
Set Raw_classification ID as per ASPRS

### ISSUE THREAD

**Issue by pradAI** [laspy/laspy#89]
Hi, I am trying to set class ID after classification of LIDAR points but few classes are not seen in the LASTOOL -lasview 

here is my script,

NewX = np.loadtxt("495500_6951500_Res_SevenClass.txt")

for idx, record in enumerate(points2):          
    if NewX[idx].astype(int)==0:
            points2[idx]['point']['raw_classification'] = 6
    elif NewX[idx].astype(int)==1:
            points2[idx]['point']['raw_classification'] = 5
    elif NewX[idx].astype(int)==2:
            points2[idx]['point']['raw_classification'] = 14 
    elif NewX[idx].astype(int)==3:
            points2[idx]['point']['raw_classification'] = 15
    elif NewX[idx].astype(int)==4:
            points2[idx]['point']['raw_classification'] = 17        
    else: 
            points2[idx]['point']['raw_classification'] = 0

out_file = laspy.file.File("495500_6951500_nongroundClassified_Seven.las", mode = "w", header=inFile.header)
out_file.points = points2
out_file.close()

I can see the class ID for 6,5 and 0 but not for 14,15 and 17. I have seen points are assigned to particular class IDs but not able to visualize for class ID 14,15,17 in LASTOOL-lasview function.

Thanks

**Comment by zwnk** [comment]
did you try another viewer like fugroviewer? my reclassification works without any issue. lasview does not color all classes that are specified.

**Comment by grantbrown** [comment]
Closing unless this can be verified to be related to laspy - it sounds like the visualization tool is at issue. Thanks @zwnk.
