### ISSUE TITLE
memory leak and slow reading of large LAS files

### ISSUE THREAD

**Issue by rezmal** [laspy/laspy#90]
First of all, Thanks for your great library. I have been working with large LAS files, half billion points per file using laspy, and I noticed that therer might be a memory issue with slicing las files, I used following code to only look at the first and last entry of x, however when I call:
```
with File(lasPath,mode='r') as lasin:
    x0 =lasin.x[0]
    print(x0)
```
it takes up to 10sec to assign x0 and memory usage goes significantly higher. However, for a smaller las files (10m points), this is significantly faster.

**Comment by kbevers** [comment]
Half a billion points? That sounds like files ~10 GB files to me. Are you sure you can even fit that in memory? If not, there's your answer.

**Comment by rezmal** [comment]
I can read the entire file on my machine (Windows 10, 60GB memory). I thought that index `[0]`, would only read and load the index `0` of the field `x`. Based on the memory performance, I think that entire field `x` is loaded to the memory, then index `0` is returned. is that right?

**Comment by hobu** [comment]
> Based on the memory performance, I think that entire field x is loaded to the memory, then index 0 is returned

Yep. There's no stream-style access in laspy.
