### ISSUE TITLE
ctype.longlong present in edim_fmt_dict but missing in other dictionaries

### ISSUE THREAD

**Issue by mikedorfman** [laspy/laspy#92]
After trying to define_new_dimension with a int64 datatype, I received a key error.  Digging in a little further, I found ctype.longlong was present in one of the dictionaries but absent in a downstream dictionary within the .util module.  Can someone clarify if I'm not understanding the nuances of how these datatypes are used further downstream?  Or was this entry (in `fmtLen`, `LEfmt`, and `npFmt`) forgotten?

**Comment by hobu** [comment]
@grantbrown might recall specifically, but I think this was simply forgotten.

**Comment by grantbrown** [comment]
Looks like an oversight - can you see if [this](https://github.com/laspy/laspy/commit/920e96742b1fa21a3f9f1aa8dba7d2b78f9a3a63) addresses the issue?

Looking at that code again, I think a lot of that complexity could simply be removed not translating to the LEfmt anywhere in the code, and leaving things in terms of ctypes and numpy formats.

**Comment by mikedorfman** [comment]
@grantbrown This mostly solves the problem I was seeing, although `fmtLen` will have to be updated as well.  What does the LE in LEfmt stand for?  Thank you so much for the speedy reply!

**Comment by grantbrown** [comment]
Closing - should be addressed by latest changes.

@mikedorfman LEfmt is poorly named, and refers to "little endian format" which is used to construct numpy dtypes.
