### ISSUE TITLE
How to implement ASPRS LAS Working Group draft uncertainty extra bytes

### ISSUE THREAD

**Issue by forkozi** [laspy/laspy#96]
Is there a way to specify the scale of an extra byte dimension using the define_new_dimension method? 

```
            out_las.define_new_dimension(
                name='tvu', 
                data_type=3, 
                description='total vertical propagated uncertainty')
```

**Comment by forkozi** [comment]
Is there a way to implement the draft version of the vertical and horizontal uncertainty extra bytes as specified by the ASPRS LAS Working Group (https://github.com/ASPRSorg/LAS/wiki/Standard-ExtraByte-Definitions)?

**Comment by grantbrown** [comment]
Not currently - you could store the scale in a VLR if you wanted to, but your software would need to be aware of it.
