### ISSUE TITLE
Add projection metadata read API to laspy

### ISSUE THREAD

**Issue by chadrockey** [laspy/laspy#97]
It looks like #68 is primarily about adding the projection information.

My use case is that I'd like to read the projection information.  I've implemented a lot of messy code that does this, but I'm not satisfied with the approach and how complicated it is.

Here is my implementation:
https://github.com/chadrockey/TGC-Designer-Tools/blob/12e4dd4dd37c741ee33c586ca56cde707735f346/usgs_lidar_parser.py#L133

I'll be honest that I don't really know what I'm looking for in terms of how many formats and possibilities may exist out there, but so far I've found:

- A few formats exist inside the VLRs
- A few formats exist inside of XML metadata
- Some files have .prj files beside them

Since lapsy is a breeze and enjoyable to use, is it within the scope of laspy to expand to provide the projection format?  I could really use more eyes on the code and would be willing to clean it up and commit it upstream in exchange for review and guidance, but I'd like to get the go ahead before starting.

If another project other than GDAL or PDAL already does this, please point me in that direction as well.  I think this functionality is complicated enough that we as a community should implement it as few times as possible.

A few initial questions for the universe:

1. I ended up relying heavily on EPSG and http://prj2epsg.org, but I think this is primarily because of quirks in pyproj, especially related around units.  Is EPSG output a feature that is desirable?  Is utilizing a webservice like prj2epsg acceptable for laspy?
2.  Which representation is the best for the standard projection representation?  Proj4?  My intuition says that proj4 would be the best standard output, and the corresponding EPSG code would be the most convenient.
3. Which of the sources for projection are acceptable for the laspy project?  Is it okay to search through external metadata files?  I've had good success using difflib's SequenceMatcher to score filenames based on similarity to find matching metadata files for lidar.
4) Are there standard formats and conventions for the VLRs and XML metadata that are in a list that can be implemented?  I've been adding them re-actively as found by me and reported by users, but it would be nice if there were a list so I knew what to expect.

**Comment by hobu** [comment]
* Yes, PDAL can take care of all of this for you now. PDAL is available on conda if that makes your deployment story any easier.

* PROJ6+ will have support for WKT parsing. The pyproj project is working to incorporate support for it. This has not yet been released, but once it is, this stack will be an option for you to consume the WKT. See the ticket traffic in https://github.com/OSGeo/proj.4/ for details.

* There is nothing but libgeotiff/GDAL/self that can rip apart GeoTIFF keys and consume them. There is no convenient exposure of those methods to the public C API of GDAL, so you would have to use some kind of FFI approach with libgeotiff directly if you wanted to try to unpack the GeoTIFF keys. 

* The standard formats for LAS are GeoTIFF keys for 1.0 to 1.3 versioned data, and OGC WKTv1 for 1.4 data. 1.4 can have WKT data in eVLRs at the end of the file too. Sidecar .prj files are not common and I can't remember seeing them.

**Comment by tmontaigu** [comment]
With #197  and #215 I consider this closed
